### ISSUE TITLE
Job History Failed to load entry point bands

### ISSUE THREAD

**Issue by superstar54** [aiidalab/aiidalab-qe#1022]
@superstar54 do you know what this is about? (This is actually Edan asking 🙂)

**Comment by superstar54** [comment]
Hi @cpignedoli , do you remember how to reproduce the issue?

**Comment by cpignedoli** [comment]
I do not remember how this was triggered but it could well be it has been fixed by recent modifications. If it does not show we could close and I will reopen with more details if I encounter it again.

**Comment by superstar54** [comment]
Thanks @cpignedoli , I closed it for the moment.
