### ISSUE TITLE
Submitting a magnetic run after one has been submitted

### ISSUE THREAD

**Issue by mkotiuga** [aiidalab/aiidalab-qe#103]
When submitting a 'ferromagnetic' run directly after submitting one using the QE-app by selecting 'new calculation' from the top drop down menu - a non-magnetic calculation is submitted. 

**To Reproduce**
1. Submit a ferromagnetic run with the QEapp (eg pk 630)
2. Then select 'new calculation' - which brings you back to step 1. The same structure from the previous calculation is there automatically, use that structure. 
3. In the next screen (workflow), do not touch the 'magnetism' menu - it will still say 'ferromagnetic'. Other options can be changed or not. 
4. Submit run - this second run will be non-magnetic (eg pk 657)

**Comment by mbercx** [comment]
@unkcpz see if you can still reproduce this! 🙃

**Comment by unkcpz** [comment]
I can not reproduce this bug, the QeApp version is the latest `v21.11.0` and widget base version is `v1.1.0`.

Essentially, the third step is different. When the 'new calculation' is chosen, the step2 settings will all be reset. I think that makes sense. 
 @mkotiuga Could you try this with the latest version and see if it is solved?

**Comment by unkcpz** [comment]
However, there is another issue when the 'new calculation' or the `Reset` button is clicked. Step 1 the structure upload widget will not be reset.
When the user tries to upload another structure, the 'Upload' widget will show `Upload Structure (2)`.

**Comment by mbercx** [comment]
Pretty sure this was fixed in e8f7ea428f05d67d2a96933e16842b57eb1f151b. I can reproduce the issue with the previous commit, but after e8f7ea428f05d67d2a96933e16842b57eb1f151b "Magnetism" will be set to non-magnetic again after a new calculation is selected.
