### ISSUE TITLE
Improve the band structure plotting

### ISSUE THREAD

**Issue by mkotiuga** [aiidalab/aiidalab-qe#104]
Some ideas to improve the band structure plotting: 

- [x] (1) The Fermi energy needs to, at least be indicated, or, even better, be set to 0
- [x] (2) Y-label changed from 'dispersion' to 'Energy', 'E', or 'electronic dispersion' (there are other dispersions that are commonly plotted in a similar fashion aside from electronic energy dispersion - mostly phonon dispersions...). If the Fermi energy is set to be 0, then the label should be something like 'E-E_F'
- [x] (3) A smaller window would be better, maybe E_F +/- 5 eV or so? Anyway, the really low bands are often just not physical, and the high bands are really sensitive to the energy cutoffs used and can show funny unphysical results as well. 
- [ ] (4) For ferromagnetic calculations, a way to distinguish between the spin-up and spin-down bands. ( you can compare  the results of  pk 630 to https://materialsproject.org/materials/mp-13/)

**Comment by csadorf** [comment]
I will try to take care of re-introducing Dou's widget.

**Comment by csadorf** [comment]
> I will try to take care of re-introducing Dou's widget.

Done in https://github.com/aiidalab/aiidalab-qe/commit/e5b6798dfbc436cd7b650e0dea024e2ff039c406 and released in https://github.com/aiidalab/aiidalab-qe/releases/tag/v21.08.0b3 .

**Comment by csadorf** [comment]
@dou-du Could you comment on this issue, please?

**Comment by unkcpz** [comment]
I am pretty sure the latest `bandplot` widget address the first three issues. I am checking the fourth, running calculation on Fe and see the electronic structure. I think the bandplot widget can distinguish the up and down spin, only need to dump the corresponding outputs and feed them to the widget.

The update to new widget is included in and closed by https://github.com/aiidalab/aiidalab-qe/pull/159 too.

**Comment by unkcpz** [comment]
The last (4) point is brought up in https://github.com/osscar-org/widget-bandsplot/issues/8. I will close this issue and open a specific one for that.
