### ISSUE TITLE
Remove the "Expert mode"

### ISSUE THREAD

**Issue by sponce24** [aiidalab/aiidalab-qe#109]
When at Step 2: Submit work chain, it is possible to click on "Expert mode".

For like 10 min I though there was a bug as nothing was happening. 

Then I realized that there was "new tab" open on the top next to "Workflow". 

My suggestion would be to remove the "Expert mode" button and always display the "Advanced setting" and Code& resources option. If the user does not click on them or specify nothing then it should still work as in not expert mode. 
It is not too overwhelming to have these additional tab there even for non-expert. 

- Samuel

**Comment by csadorf** [comment]
Thank you for the suggestion. As an alternative we could also make sure that the browser scrolls up to reveal the additional elements.

The expert mode is indeed relatively thin at the moment. I am open to completely removing it as long as there is a clear visual distinction of settings that users are expected to typically modify, and those that they should only modify in rare cases and/or if they are very familiar with the underlying algorithms and models.
