### ISSUE TITLE
Inform users in case that pseudo potentials are not installed and provide UI flow for installation

### ISSUE THREAD

**Issue by timrov** [aiidalab/aiidalab-qe#118]
## Automated report

_This issue was created with the app's automated bug reporting feature.
Attached to this issue is the full traceback as well as an environment
fingerprint that contains information about the operating system as well as all
installed libraries._

## Additional comments (optional):

_Example: I submitted a band structure calculation for Silica._

## Attachments

<details>
<summary>Traceback</summary>

```python-traceback
/opt/conda/lib/python3.7/site-packages/aiida_quantumespresso/workflows/pw/base.py in get_builder_from_protocol(cls, code, structure, protocol, overrides, electronic_type, spin_type, initial_magnetic_moments, **_)
    178             pseudo_set = (PseudoDojoFamily, SsspFamily, CutoffsPseudoPotentialFamily)
--> 179             pseudo_family = orm.QueryBuilder().append(pseudo_set, filters={'label': pseudo_family}).one()[0]
    180         except exceptions.NotExistent as exception:

/opt/conda/lib/python3.7/site-packages/aiida/orm/querybuilder.py in one(self)
   2182         elif len(res) == 0:
-> 2183             raise NotExistent('No result was found')
   2184         return res[0]

NotExistent: No result was found

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
~/apps/quantum-espresso/aiidalab_qe/steps.py in _on_submit_button_clicked(self, _)
    478     def _on_submit_button_clicked(self, _):
    479         self.submit_button.disabled = True
--> 480         self.submit()
    481 
    482     def _setup_builder_parameters_update(self):

~/apps/quantum-espresso/aiidalab_qe/steps.py in submit(self, _)
    585         builder = QeAppWorkChain.get_builder_from_protocol(
    586             structure=self.input_structure,
--> 587             **self._deserialize_builder_parameters(builder_parameters),
    588         )
    589 

/opt/conda/lib/python3.7/site-packages/aiidalab_qe_workchain/__init__.py in get_builder_from_protocol(cls, structure, pw_code, dos_code, projwfc_code, protocol, overrides, relax_type, pseudo_family, **kwargs)
    115                 overrides=relax_overrides,
    116                 relax_type=relax_type,
--> 117                 **kwargs,
    118             )
    119             relax.pop("structure", None)

/opt/conda/lib/python3.7/site-packages/aiida_quantumespresso/workflows/pw/relax.py in get_builder_from_protocol(cls, code, structure, protocol, overrides, relax_type, **kwargs)
    123 
    124         args = (code, structure, protocol)
--> 125         base = PwBaseWorkChain.get_builder_from_protocol(*args, overrides=inputs.get('base', None), **kwargs)
    126         base_final_scf = PwBaseWorkChain.get_builder_from_protocol(
    127             *args, overrides=inputs.get('base_final_scf', None), **kwargs

/opt/conda/lib/python3.7/site-packages/aiida_quantumespresso/workflows/pw/base.py in get_builder_from_protocol(cls, code, structure, protocol, overrides, electronic_type, spin_type, initial_magnetic_moments, **_)
    182                 f'required pseudo family `{pseudo_family}` is not installed. Please use `aiida-pseudo install` to'
    183                 'install it.'
--> 184             ) from exception
    185 
    186         try:

ValueError: required pseudo family `SSSP/1.1/PBEsol/efficiency` is not installed. Please use `aiida-pseudo install` toinstall it.
```
</details>

<details>
<summary>Environment fingerprint</summary>
<pre>eNp9WF1v67gR_SuB-7oyLNmJk7xts92Hxb3t3c3dLoqiKCiJsmhTIk1ScZTF_e8dzgxl5gYokhcffs-cOTOjP1cv0nllxtVj-
cPKahE644bV458r4ZpeBdmEycnV479Xd7tahdUPq9V_YN4cejP-d1m62q736wcYvCJ_KW-eP3-5-TrJm18mfVNtbqrysaoeN_c3v
399gt9VufoGO4nmJA7S44lKtaKoxdj6Qo3ewtmw0Wa9W29gax5Vh7YjuFrfLXBj2mCMhm1W1brM5jcm3n5Vru_W2ytoqxOC23ymm
30Qutzj5mW-
SdvKBue_A1XXIVhlYKfl5D6gBzF5r8SIA7t1uQxoMQzW44H32XztB4NzNxk4itGAO_pCDlbgkvz2xgY1qDf5wWDWy6k1CN-tqwU-
y3M6QVzvc57EGKZBeuuk9wYdu8tWOeHx7PfPC_VgWqn9h0sll0T0av0X2OSDny5iHJV0Dxsc2WQ2msVQmw_eepPGWvbJcj8t6ri8
BDJuM6yQeiSnXreN8FkWF-NOTS8UuWaTj15Ue5DBAx-9TKZyDW1gCqtO0RB3i98gas5ory0dAlsIH6TDg_frEi-p26McZoQeeJoc
akXkul3fR2RU3tzfbUrAHpIhRq-qPgyamYwnWtsq55lSu4jEgH2RhRWh5wDBxe5gxqpouk5F42yS2Z0zFzYgTsNXwuUfyHZ-Hpvi
IEfpRDBE6RLXhYCnVsnVfxW11Og1elINEd0IrfkKG4S-D2kyUg0xZwMeyxPVKNxsHDCdiRwfVmspmj4zbm1OsscjiVf12WpeUQKG
OzkTtLIzmx-habDVVaBKNu4T7C2fzBic0WmLKCxNxNvCOmOlCzO7qEojidsQHgzqprAy27hptKrx9z7-gk0Uu6CKO-E12StgW3pq
00EYSz4LJ_TCtTLgQRtG5KDGzrx7W6NcM1GolXs6XasmityeAwR_gxwOVstAFtik9_DQ2KlD0SktWS02y5i3ahyZy8yDxmjjxCAy
P8EOrcCbPtC-8XfBCl_0QAKtxgNZJE2AI019BAyeS2Y35qRkMwWKnRTLyBRzcML2c8aEZm50uheZp5X1dLBzJhgg3iaReMdy1kpp
WcBv2dKt7CYv29dBp5BFEJSwEWywJFk_HcV4MAjAHy4GbmNOzGa1Bl6hWABLMnU76YtqODzhPz5NggbIMXDYxi0RHYTSoJUa5GgJ
QBoBqs7WqDGwtkYsyC2FLx7TgfQIq8iPZIWftfAn3mWXfhdPBoN5Gym7zCp--
9vz127SHKkxr3e-WctXa1zI1D-CfdvdFspktO8mqhjio-_xNui1F_VGWHRyf2uTF-NG_TSIsXNKAkNm1L24TLWjIHPGOWqIZQJlu
HQBNcQbQZQVgwwC7CTIBnSR6ygkMzO5JlYZ4G5eOyqiX6aBoBdxE1Z-Du4NDZykG1HnIC7oeovDgcy3aVqEomxePb_sEJyUmS4Dc
j1oz_XJFSzkawB7yDYrPFTwLTBPOjP5DD7KViV7x9-_qPEoKjIdUeaISMHaku50NHVSKLLY0ZsxOxaDIOE-6o7ItPo4wZOkK0Ahg
JFomJLS3DJCtdeOY4nhmFvtfIiU59BYV-9Hr2ZJFdBJXa5avmPAG_3CGkFioIU7gdw4nxSBHq9Nc1pUrSS11hTmOzb7Z3EyWWx8h
o1acxmZogma7LPoZMaXQfhGZVXOjqg6iBDzEdl2ywXfFYRECDoos7cP0eJaypdM0Qflw8Sz7vEKA-SoOeUPSnwDWLiAIt2lO9xzP
TLYgeSkZLYN_hCFmG2Kh046qFZhQr5lJo314s2YHLYEmRHsHJj6e8RikyDSSpwmfSiwaGAx2DEcnn76eccJbU9ILLpekZ63eLfxo
F-UvLAO4TKodGtIBHgmVbMjZG9S9YruarRcvLqLooIlsGjZsGT1hF1Zytk3XsVAZnWQ4v2SX6NdKF9RogKJfkAIcmYQtZaZaFkxn
C0XIfQbsp3P8k4ETAN3BP_4zCbAUDGoE-
WPPZ8JpF3qYgrGiBl2P80JPbCn4iPvGLqyj7hka4duofQNpYsy0cl8-XLBX7kW2zFj7MFPmTZYSPtaeqg-JJPyFtAvSmusGu855L
4oJkt5R5dWlirwCimLjJ_xlJIfr6fDgSK5pC0AGTi2ofbEs81smIH40xmQ915OvsjYyQ1aHLQBY_CkQkplsZC2Pmow2oJf6OfG2E
NVUJWJdrwnO4YZ9oH84LMAZLZxWWHnRihH1K7IQV_mJ9X99gdXFVuaZLwIXD4xsggSlwoxx4yBa352LaYdqLJ6Nb4W8NQh9XG0B2
QpLQNzwRof6PhFQ-M70JRzP2HhXW1ivcGYgmIgp98MkQsZimKBKmbc7vP8_Osn7k0I-bt40rySbv4PK8fn508UGUzTOT6QwwUm7h
EDBJqf5Ko9H-wHCFifJZwv8zOIs-c6j7YL0pPWMIUopYKBJPuzWqyGI5D8Un20yVcMcqASnsTn4TrigYOqm7noTFtBdj76PJ7nYI
6NGCwHF2NOzFkHA8Ab2TvZ7F8_fv7Eukg7v2FfWFUsbdB0Xr9UYEsZp8Hhsapj9SDkPIElaF5FQpmwAh-WVfBOwuJUW1NqcJMYpF
5D96yXAN28x9fcoGy4haGh2HDrItXyWLnex4WQ6iDCCujFHDUPFZXSgHOoEOW9FLXhKSXlSS_lyaZ89IAUeYaUV311wveZ80GIJ7
s0Vg9Rq5DuUbM35SZGte-ljl1EL4aMmb6HSm-aVJtxy6vY6sTShYpCUlqvXimsSVv8aC41NKtA1mHgKCVXe3tIxRFr2zOGJ1dAeA
LFK4jKXEO_wj0VmZ_HIJF1ZhqhjYTqNesreBhSRPpuQo4kvIndKBQK0ONrCQ-2Wdp-PwNaQ2gTfNEqaFMCdP8ZWb-f-
fJ_d4qfF3hCxVXX-wlHv5QUm-wNafgcsu23H4ZBAhX0Mm_RdelDRok5heZB2QllOjxDdF2qUZEnv376UcfSc4mN3Tu0-H0ptLd3-
AHFnzVKbqrIIhSEixlcprwTRd9PNYv-tkKn3qJ6-DnVGXEzyJuTFiGVYVFEIJtD_y34mxr3GlG0lu8uRK0QnzSNKrafLeXeaJYoN
KK1QPImaO73cLpJgUreAU3jQ4h94dwOmGpu-bcTKujUphDpEINcJn3WZ8BvMDq1E_HTh089Ejk5vEF9LOgmcfo0xi8VAvK6kjwV3
TTZDoSr4HhKOWJyEI31ltIixf8_BbRdc1aRvBgNUT2Z9H2CzrmI0PStOaQ3R9tfGij9l49X8dSLrOUI9oMXpDCJi_-Q7vQmp0PGx
ksvpU48iMdSF0Gfk5fPQ5TreOj74qjip3L_MdaLzZgfeA40s5ROS3oedBJLbxQ1MD5kBr5lkvim8FsltQLfvv0Pe2SkUQ==</pre>
</details>

**By submitting this issue I confirm that I am aware that this information can
potentially be used to determine what kind of calculation was performed at the
time of error.**

**Comment by csadorf** [comment]
@timrov The issue should be resolved in your environment, however I will leave this open, because we should show a graceful error message when the pseudo potential families are not installed.
