### ISSUE TITLE
The povray rendered ignores the supercell settings

### ISSUE THREAD

**Issue by csadorf** [aiidalab/aiidalab-qe#127]
Following https://github.com/aiidalab/aiidalab-widgets-base/issues/252.

**Comment by csadorf** [comment]
@dou-du Could you have a look at this, please?

**Comment by dou-du** [comment]
> @dou-du Could you have a look at this, please?

I will check it and come back soon.

**Comment by unkcpz** [comment]
closed by bump aiidalab-widgets-base to 1.4.0 https://github.com/aiidalab/aiidalab-qe/pull/292
