### ISSUE TITLE
Setup a new code should not show non-compatible codes

### ISSUE THREAD

**Issue by giovannipizzi** [aiidalab/aiidalab-qe#132]
**Describe the bug**
If one reaches the "setup a new code" notebook from the QE app, only compatible apps should be visible when pulling from the DB. I see e.g. instead also CP2K.

**To Reproduce**
1. Go to the QE app
2. Click on 'setup a new code'
3. Click on 'pull code'
4. You will find at least one non-QE code.

**Expected behavior**
I think one should see only QE codes (when coming from the QE app)

**Comment by csadorf** [comment]
@yakutovicha If I understood you correctly, you said this was resolved, however following the steps to reproduce the issue, the "Setup code" still shows codes that are unrelated. Is there maybe a misunderstanding of what is meant?
![Screen Shot 2021-11-03 at 13 15 44](https://user-images.githubusercontent.com/1441208/140058295-01c99f9f-8e77-4c31-9852-b413b717d386.png)
