### ISSUE TITLE
Materials Cloud structure supplier crash

### ISSUE THREAD

**Issue by louisponet** [aiidalab/aiidalab-qe#134]
**Describe the bug**
Crash upon selecting materialscloud from structures supplier

**To Reproduce**
1. Start QE app
2. Press OPTIMADE tab
3. Select Materials Cloud

**Version (if known)**
 - App version: [e.g. v21.10.0b1]

**Comment by csadorf** [comment]
The issue must be resolved upstream and is now tracked in https://github.com/CasperWA/voila-optimade-client/issues/369 and https://github.com/CasperWA/ipywidgets-extended/issues/48 .

**Comment by csadorf** [comment]
The issue is now tracked in #149 .
