### ISSUE TITLE
Showing workflow summary in setting step

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#153]
Now the workflow summary is shown in step3 results & status. The parameters there are all related to the settable parameters from step two. 
It would be better that users know the specific parameters they setting for the workflow immediately rather than finding that from a summary after the process is submitted. 

Currently, the `SummaryView` widget which show the summary read the work chain node as input. To implement the feature described in this issue, the summary should be created from the `builder_parameters`. 
The `SummaryView` can get the workchain node as an extra input to show more process-related information in step 3, such as the resource usage.

**Comment by csadorf** [comment]
The purpose of the `SummaryView` is to show a summary of inputs and outputs for a given work chain not just the builder parameters. I am not sure what the additional value would of showing these values in a summary also in step 2 since there they are already displayed through the control widgets.

**Comment by unkcpz** [comment]
> I am not sure what the additional value would of showing these values in a summary also in step 2 since there they are already displayed through the control widgets.

I look at the issue again and agree with you.
