### ISSUE TITLE
Creating a bug report fails when Traceback is too long

### ISSUE THREAD

**Issue by mbercx** [aiidalab/aiidalab-qe#156]
**Describe the bug**

When trying to create an automatic bug report after the app crashed because of an error, this step fails when the Traceback of the error is too long with the message "the request URL is too long" (see screenshot below).

**To Reproduce**

1. Follow the steps in #155
2. Click on 'Create bug report'

**Screenshots**

<img width="471" alt="Screen Shot 2021-11-18 at 11 43 44" src="https://user-images.githubusercontent.com/25607960/142400781-805818d4-7f61-40d8-92fd-f1337e7a8463.png">

**Version (if known)**
 - App version: [e.g. v21.11.0]

**Comment by csadorf** [comment]
@mbercx Could you manually adjust [this value ](https://github.com/aiidalab/aiidalab-widgets-base/blob/a26acdb8c120d07155b6a42c7d12c4bb174b32ef/aiidalab_widgets_base/bug_report.py#L150)from let's say 3,000 to 2,000 and then check whether that fixes the issue?

**Comment by csadorf** [comment]
Should be fixed here: https://github.com/aiidalab/aiidalab-widgets-base/pull/266

**Comment by csadorf** [comment]
Resolved with https://github.com/aiidalab/aiidalab-widgets-base/pull/266 .
