### ISSUE TITLE
The pw.x code is not automatically selected

### ISSUE THREAD

**Issue by csadorf** [aiidalab/aiidalab-qe#164]
**Describe the bug**

After starting the app the first time, the QE installation is triggered, however the pw.x code is not automatically selected.

**To Reproduce**
1. Install the QE app in its latest stable release (`aiidalab install quantum-espresso --yes`).
2. Open the QE app.
3. Go to app step 2.
4. Wait for the setup processes to complete.
5. Inspect the code selection in the "Codes" tab of the expert mode.

**Expected behavior**

The code should be automatically selected after the setup process is completed.

**Screenshots**

![Screen Shot 2022-01-07 at 14 44 53](https://user-images.githubusercontent.com/1441208/148553764-a237a790-1800-47d2-850a-b1679e9ed7e1.png)

**Version (if known)**
 - App version: v21.11.0

**Additional context**

This issue represents a regression.

**Comment by unkcpz** [comment]
But refresh the page after the fourth step, the pw.x code will be set.

**Comment by csadorf** [comment]
> But refresh the page after the fourth step, the pw.x code will be set.

Ok, but it should work without refresh.
