### ISSUE TITLE
`QeAppWorkChain`: restart for PDOS `nscf` fails for non-primitive starting structure

### ISSUE THREAD

**Issue by mbercx** [aiidalab/aiidalab-qe#195]
**Describe the bug**

Currently, the `QeAppWorkChain` tries to reuse the charge density calculated for the band structure `bands` calculation for the `nscf` calculation of the `PdosWorkChain`. This fails in case the original structure is not already the primitive one, however, since SeeK-path will primitivize the structure before running the `scf` that calculates the charge density. Since the `RemoteData` folder of this calculation is passed as a `parent_folder` to the `nscf` calculation of the `PdosWorkChain`, but the structure is still passed from the `PwRelaxWorkChain`, there is a mismatch in the number of atoms specified in the `aiida.in` and the structure retrieved from the `data-file-schema.xml` and the calculation will fail with:

```
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     Error in routine read_conf_from_file (1):
     bad number of atoms
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Expected behavior**

The work chain should either:

1. Calculate the charge density again for the relaxed structure
2. Use the primitive structure to calculate the PDOS

I'd use the second approach, since it's faster and I think it's also important to have the PDOS match the band structure. It's also easier to fix. 😁 

**Version (if known)**
 - App version: `master` branch

**Comment by csadorf** [comment]
This bug is present in version [v22.01.0](https://github.com/aiidalab/aiidalab-qe/releases/tag/v22.01.0), correct?

**Comment by mbercx** [comment]
Yes
