### ISSUE TITLE
Bug report (structure-editor): Application crashed with IndexError

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#217]
## Automated report

_This issue was created with the app's automated bug reporting feature.
Attached to this issue is the full traceback as well as an environment
fingerprint that contains information about the operating system as well as all
installed libraries._

## Additional comments (optional):

_Example: I submitted a band structure calculation for Silica._

## Attachments

<details>
<summary>Traceback</summary>

```python-traceback
IndexError                                Traceback (most recent call last)
~/.local/lib/python3.7/site-packages/aiidalab_widgets_base/structures.py in translate_to_xyz(self, _)
   1059 
   1060         # The action.
-> 1061         geo_center = np.average(self.structure[self.selection].get_positions(), axis=0)
   1062         atoms.positions[self.selection] += self.str2vec(self.dxyz.value) - geo_center
   1063 

/opt/conda/lib/python3.7/site-packages/ase/atoms.py in __getitem__(self, i)
   1073         atoms.arrays = {}
   1074         for name, a in self.arrays.items():
-> 1075             atoms.arrays[name] = a[i].copy()
   1076 
   1077         atoms.constraints = conadd

IndexError: arrays used as indices must be of integer (or boolean) type
```
</details>

<details>
<summary>Environment fingerprint</summary>
<pre>eNpdWFtv4zYW_iuB-1oZlnyJnbci-7SY7M42nS2KYlFQEm3TpkiGpOIoxfz3PTcpyiB50Ufy8Fy_c-i_F686JuPd4qH8eRGsykcf
u8XD3wsVm7PJusl91IuHPxe7TW3y4ufF4n-wb8hn7_6aji7Wy_vlARY_kJ_Kcl98q3uX-7vnp693v-v27knFu-quPDysqodNefft
t8e7alVVi-8gUTVXddKJbjamVUXj8d5FudwttyCZwZB033qAVwCvJ_ilV3BPp1OIOiVPCm2X1bhuVQ1QVS5L-J-BhbaOZP0Av-
DFVbVc_wgXNx-vzVkZR5qt5qs30550TkWtEuu9FgV8EcxVAbRb7uUIuPiFlJQbbHvR3UCqHATRXW0aknPP9rtkqnPurPiEBIXQmp
gI2Sw3iGDQXnURVD6TuIrFxVPju2B1JsuWKz4eT95VRXM8GnbP-
ke4qI1rjTslXq9kPfob3SnCyV6w5MARSYNripN2OqrsI20s6VzO8ZOgGmLeKGtFUYKaOIRM4gQwTsXBR-czbWMza6tVgwZulhyF2
l_1mUzbkNfrl2DlRAlxRDXr6LM1gb18z6f6LkDG4rkVZUeJwh9BtH70LkdvRwlkQIML2Xub6OaKVGl0zIYdSDJWyz2i7FP4ZoWb4
-l1FnBIodjqTGI4FogknQsHqaGseWetYJFvPuvOuKP_pH1jYtMn1vCexVrTXAGAL_ICfRcSeS7LldTFuOSO5lQcjdVSU6tpLQXjH
KlB9UEL3vqoOjWLBEhoFdlxYLn4XUg1F2flWgv5I3ksG-BKX18A24J9O8L81eimz1lH2YqZRLngT1GF8zB33tDYUS-Ofqsak_WsM
Fpd9ydyVgn2loQAn0g-biVpWn3sk27fOite5Y3AIY0Sd1XjVpMgeWratybD_3FR7uRpC_wh0rrEvDg_19ubaaQU4R9zQ0Nta5elR
DFjcafulLHFK8S-_SgbcgPsBUd44zIHm7Cs11x05NSjSlkFwzHc0g6MqfWUDmuhoiPk9Cx99wz2TPDoTUbI4a_mnbEDIVo7S_lay
o2mBbXMcRALypIwp9h2NMh0wUd0WtHprMAoTpOS8_1jFRjb97FB6ofIVKQ8lCkeEEqValvxwlVHpy3R6Y4iZiavQ9qsxm0IIQv12
dg0YxhcAnNm5AjIx0X30m4-wEK_Ze1a3Yr1eOSiWzO6DL__adxFVWw7B-1CSJFNp2eXX3zNWVRKflySdxRaqfdKsKiPfEy-
EzKAmvHipQc7dCygViEQ5A2QWc1XuH9upKMIPOtU3MLoiqu5fTDjRoDk7avUI-ePVfEKpQ08FUdeRFWsfjPtB_-tsKIx8yZWKdmu
J3X1YvqOPuO19TcnCTpCfXhWx7FLoeKdysjl7Dds66tPYGEcMIxcRK7voFZ7QfZkTQeJP4waQsTuCYu6ANaIY0XsR3u60HFpjg2u
SyckNPEXXdHbbFrTZMlZPOZqoDZwGGOcmq7GaUplIR086nTKBfVI46VxM5xxtngjw3m0cSf7avSNrOZrnW-
hEF9nRAdtUdfAnpQAG8pcB02NmQ-MRcBbPYVig272AdJSteKzHTWsEftIKHEWURvzORN5xXYEGFFyVrXVEsAVgd1LIBPGb-
gGSVJoK4BvQB1wfBJ65o3QV8yV-ZRrChPNSxAr-s5niHcl4u-XwadcysIYxJXQU6iZ6HngCvot6IbbrSCn1M8oIEDDszpBD9ZSBK
jsV2MtTTp74eivxuXRaXwsjIMTfcr0LDNZJa2HEnUgdVhMsBIi6gmE-
MFLc6ZPSE3o2p3JI6WQnOiBSc-6Tx9BmooQF0Mu0A9XkyVnKgpUQgqceyMNjQ-
nquDZSlyOiRHyAHKAitNszAhDo0zkXK24JL8Oj-b46-_kT05f2OSTyrPBHJCJKqD-WVILY7pMtQf26HDCXpikbciFUDHA3JyDRAM
72vo0PP_niwzJa0L-pR6tFBGf_HfQ7vn5Cx0V_ggD6sG5u5aBIwyApDz5UBwzpA4KZSRGtvQZmCzJUMLiqLNAe9Li12pMUF5Jtj9
xY9wKu-
ICtJxLmlfGkP2lUV2QpBUsqkFmDDn4TqaUo8F__PL0RTKJlXmnh0Q1ioUnylgKNOXHBuVg-85xmFF51NR-1cipuz2BLz2wEx-
umGBGrKDhdzZATgudF2pkJ8Zjsz7s7-UuEturTtvloGTOwuJZf8aXzThccavgpQKXinHChIOQwXhFagzkeAFvgMgjbcVDP-DCfDw
_Jq2vYaTywxJZ_xk6efVbVOk8Uxnm7j5Mg9EBqZXIBRlwVa72n7YUqemIbdmR6awtTrhn1c0SMZ3Bu31vWkklEmFwDMdmzoPbPWV
iMm_cE7nyUzhNA8KOLoCU_8Vi95_Ct_mEFt-mAWfNo0t6sVR5MqWTlllFpGuh_BGM0MEKDNh6feCKR3gY-weOfsDwPdDa2E0J0g7
n7YGIkcsE2BzeJ0pe5mUlYMrTO5TNyzBLFb0zOI238kpGGMpDtQHc22QrZUrb_ZgyXEj4baQx83eUS5mP80vbESlt5Tsqky2POls
Z3QgDntNpxv_wDTH8iyY9_P0iycuM1t5hmFFc6PjdO3zyKWgFhmSsZZ7pwxFqr5AAjxzVR0iPes1KMzP-V0HtDbNm9WogWaCdUmd
HiuXUuqncnFt_Gj2Acb81MLxNT3uM9k3X9CxjjpJWAaB24GJ5uq-kE93OWtsxVegKmgSLGrpymh7MFaWrLAUdjcdJRzo9Pmy203J
y9eSz2Y8uN3hB5FEfBOCJNU2wpbwUB0jJ2bvw3YRAIpB3vn__P9A6NmQ=</pre>
</details>

**By submitting this issue I confirm that I am aware that this information can
potentially be used to determine what kind of calculation was performed at the
time of error.**

**Comment by yakutovicha** [comment]
We should close this as soon as https://github.com/aiidalab/aiidalab-widgets-base/issues/309 is fixed.

**Comment by unkcpz** [comment]
Closed by https://github.com/aiidalab/aiidalab-widgets-base/issues/309
