### ISSUE TITLE
Bug report: Application crashed with TypeError (Using custom SSH key when creating new code/computer)

### ISSUE THREAD

**Issue by Crivella** [aiidalab/aiidalab-qe#240]
## Automated report

_This issue was created with the app's automated bug reporting feature.
Attached to this issue is the full traceback as well as an environment
fingerprint that contains information about the operating system as well as all
installed libraries._

## Additional comments (optional):

AiiDAlab docker image:
aiidalab/aiidalab-docker-stack@sha256:f436c1384e7545dc5ec6744f65aa1090005cc9dba577c77f8324be07fd6a0ab9
Running aiidalab using:
`docker run -p 8888:8888 aiidalab/aiidalab-docker-stack`

Qeapp: v22.05.0

The exception happens when setting up a new computer with "Detailed setup" and "Use custom private key"

## Attachments

<details>
<summary>Traceback</summary>

```python-traceback
TypeError                                 Traceback (most recent call last)
~/.local/lib/python3.7/site-packages/aiidalab_widgets_base/computational_resources.py in _on_setup_ssh_button_pressed(self, _)
    463             # Write private key in ~/.ssh/ and use the name of upload file,
    464             # if exist, generate random string and append to filename then override current name.
--> 465             self._add_private_key(private_key_abs_fname, private_key_content)
    466 
    467         if not self._is_in_config():

~/.local/lib/python3.7/site-packages/aiidalab_widgets_base/computational_resources.py in _add_private_key(private_key_fname, private_key_content)
    604             # if file already exist and has the same content
    605             if fpath.read_bytes() == private_key_content:
--> 606                 return fpath.name()
    607 
    608             fpath = fpath / "_" / shortuuid.uuid()

TypeError: 'str' object is not callable
```
</details>

<details>
<summary>Environment fingerprint</summary>
<pre>eNpdWF1v47oR_SuB-3pl2LLj2Hm7SJ-KTbttdm9RFMUFRdE2bYpkSCpe5WL_e-dLinIRv-jwazhz5swwfyzeTMo2-MXj-
pdFdKocQ-oWj38sVNJnW4wufTKLx_8udtvGlsUvi8X_YN5QzsH_Pi1dbJYPywMMfiB_We-31fem96W_e3n-evft3N89q3RXb-
_WD4_b_eNmd_f929NdvarrxU_YUumrOplMR1vbqkoHPHixXu6W97A1gzGbvg0ArwDeTPBrr-
CgzuSYTM6BLLpf1uO4Uw1A9Xq5ht8MrIzztNef4Fc8uK5hi9VnuLqFdNVnZT1Z9mn0ZtuTKblqVGa7N2JgqKK9KoB2y70sAR-_kp
EbPti1F9MNZMpBENM1VtM-D3x_n219Lp0Tn9BGMbY2ZUK2yy0iGLU3U0VVzrRdzdulkw5ddKbQzZYrXp5OwdeVPh4tu2fzZ7hqrG
-tP2Uer2U8hRudKZvTfeEmB75wHryuTsabpEpINHFN60pJnzZqIOZaOSeGEqTTEAttJ4D1Kg0h-VBoGl-
zcUZpvOB2yVFowtWc6WpbCnvzGp2sWNfLDZrZpFCcjezlB1r1BJuYp-
BLCm6cS6ZqHCghuExn1HSoNqlYdtUKubRa7hFl78E3mwbsSK0ptI7djEg2pfIQdeXsu0kSAz7qbDrrj-
GTYdom3Wc26YGcrJ3VVwDgiy5I35UElVNuJZQfh_zRnqqjdUbSZTWN5Wi9JzOI-jQQfKvI6ANvgt-VZGV1Vr51wAPho0yA_UNzAQ
zyZLkjLFyt0X0pJslUZATFNJySiudhxno9aDcawVFslbbFzAjemqY_kWfWcLk1IaALwqt7CX5rjn027Y_OiQt5ImiBVuKbWqb-9a
L8KRAAfxiv1meWs9mstnc3qyWB4IdxNpCRxhdJLNQGvJrplHXVG4S1_SA7jwCrhhisLxxHworZcKqQC48qFxUth4f3w3C5QJFGN9
Es4OeMinsGe9Zl9B0j5N43-87YgRBjvCMqruVE23rF98Rr2i6GBDnRVJ0pCi7ABFgzbT9GQVNDnzSKM_i8JkMhkXCBiJ5kyYoHri
Z540jwdhQLO3kYCLEapyGEOtEX6_JMA3AITJ_JFyAfBz1IQfgAK_OjGN-aVm6KSy6mtaN78Ptv1l9UzXfnAF0IqYrtzOzwS2jgyr
IRATl4CqOkbS1YMkdeJt8ZE1nNlOvSwz1MqiDlgAvkDdizno9whduK5gs8qyVcZOiIq719aNdWgBzcm2Qac8WpdIWkBblJo56hKc
ioSQjWfIdndQ1yzR19pmsbbl6IN0J9fFHHsWagkZ0qqKzso41UyA-wsh50Qg4iN3c2l16QPVneAaGHUUUhOg-EJVNB7qeR6fvR9i
52nHJjuenyCWVJfENH9K7Y1uoi_MRlvgGBAucwxjT0DTY3qoh04FJvcqmoYtkgZZThgpX-B12cGw1_cm_W3OjWfCyUJNOA4lFot8
RJ33eiVnA1BIIzk-O36NQQgXCqFQ_tqISM2AdVxDUkUKzBLL41Wx2hPShFNc5IuFYEdq-RDB6_QcGzkONegKDBHHBzFknliUl19s
qqyNmCFAoSspq-y3mMzEq0JDaswdzTRPMjGs1lT5BT7mc5HKHwOJOhFhphMdr01TpHzQRQg1Z9tb6MvuFlcexN6BNpNtC5PD86cT
kpNSFhCFIN6TMFULez6fOHe6fEwMFYKrza1RaJbU0uzihL8wvmQYd4qivuSMRZGNJYBtgH5DHPKngctLKJOVVz6nwdnuzxX_8mFz
HNYFLIqszaWUCm9IU85Z1aaG6lFzywk4YT1qIsUi4HArNBTZk9lK47mvo8vPzzi7SWG0L-rp6ckJ1X_iMa__LyhZZKnscB7WDWba
S8xwGQXCYfimOG3AHFR7Him76A4mRpAXg7UnsoGUb8Wo_U4pHs-pM9DtJMjANQBi55zumhhItWXRQeCpYUM2AzLnynq6zHC__n1-
cvwhk25p3a73rcFhr7kd3UGyeN-2D5LGmYyWsyVBLVqH27PYGvPagIL665bxmxihrJWW82DXRBJIydmI56c9g_yFm0ba8645aDkq
4G82HzGV9qlmFMsXoaqnCoGvs5WAgMxiOytsDxCjrnxN1iza0y4KJZ3K1lY65xlNzDEtX5Bapr_S2pfJ6ZDC1tH6fG5IAd2zKGXF
C7VuvV_tOUKuuOdJIdmc_GYT95Vt2MiPkM3u172wqVaAuLHS4WWG6cHoiJ2f7g2sU5nuNpKto7OgAo_6vDijyFb_sJrb5PTceG24
n86ijz5JVBVhaVUGhFrEcwQaWpMGCbzYEzHuFhVH5svUCbe3hLj1WPIOOxux1I6zhNQIeh9Vfynl3XAuYyvd74egX6m6r3FnvfVt
6WCEN6qDaCe3VxkqY0PYyU4UTCbysFlL-THMoSW17bjkTpXr6TssVx-3Ev7RRhoHMmzyQdviGGv1P3hc_-
LI8eGnuHpkNxouN37_H5BA_nYmmPjfQdfTxC7lUS4FGj-gT0aDZsNCvjbwpyb5jVn5sq-tyG03hVDPBNQ-c0vXwxrDcDjYALUvDk
_Q-g8eBLedmu5G1xOxvjRk7QEdSGwYvet3l6T9bESxmKJtmArYcUY3xB3E_D2TeTc2b_k7hBq15GexCAl8vUPk5GDkC-2Xvr3cZI
e6DC_Pz5f44_-fc=</pre>
</details>

**By submitting this issue I confirm that I am aware that this information can
potentially be used to determine what kind of calculation was performed at the
time of error.**

**Comment by unkcpz** [comment]
@Crivella thanks for the report! This is a known issue, we are too hurry to forget to address it when fixing the SSH setting.  Do you have to configure ssh configure with private key? You can try to use the password to set passwordless ssh login.

**Comment by unkcpz** [comment]
This will be fully settled by changes happened in https://github.com/aiidalab/aiidalab-widgets-base/pull/511
