### ISSUE TITLE
Improve the Bandsplot widget for QeApp

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#248]
The bandsplot widget is now used by both QeApp and SsspApp, list following some small features need to fix quickly for the QeApp so the results of band structure/pdos calculations are showing properly.

- [x] #322
- [x] There should be tick marks (?).
- [x] pdos showing the spin-up/spin-dn side by side for magnetic materials.
- [x] How to curated and group the orbital pdos.

**Comment by dou-du** [comment]
https://github.com/osscar-org/widget-bandsplot/pull/13

**Comment by dou-du** [comment]
https://github.com/osscar-org/widget-bandsplot/pull/37

**Comment by dou-du** [comment]
![image](https://user-images.githubusercontent.com/56022756/198999877-623d4170-b473-4a88-ad25-5b26feefc0c6.png)
