### ISSUE TITLE
Allowed to run SCF calculation only

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#264]
Redirected from #245. For the properties to calculate if no properties are chosen a warning message is raised and blocks to go next step. It should be that even not selecting relaxation or bands or pdos should still run: then the user can still download the QE output file.

Besides changing the widget to suppress the submission blocker, we need change the logic of the QeAppWorkchain to allowed only the run SCF calculation. Now when `relax`, `bands`, and `pdos` all not set for input ports the workchain will skip to the final step.  @mbercx any idea how we organise the `QeAppWorkChain`? I think we can either add one more `if_` for SCF only or run SCF from relax or bands sub-workchain.

**Comment by mbercx** [comment]
One way to run an SCF calculation without having to change the work chain is something we also use in the common workflows: simply set `RelaxType` to `NONE` in the `get_builder_from_protocol()` method. Here's a MWE:

```python
from aiida import orm, load_profile

load_profile('dev')

from aiida_quantumespresso.common.types import RelaxType
from aiida.plugins import WorkflowFactory

PwRelaxWorkChain = WorkflowFactory('quantumespresso.pw.relax')

code = orm.load_code(8309)
structure = orm.load_node(1)

builder = PwRelaxWorkChain.get_builder_from_protocol(
    code=code,
    structure=structure,
    relax_type=RelaxType.NONE
)
```

This will still wrap the `PwBaseWorkChain` that runs the scf in a `PwRelaxWorkChain`, but it will simply run a single `scf`-type calculation:

```console
$ verdi process status 8868
PwRelaxWorkChain<8868> Finished [0] [3:results]
    └── PwBaseWorkChain<8871> Finished [0] [5:results]
        ├── create_kpoints_from_distance<8872> Finished [0]
        └── PwCalculation<8876> Finished [0]
```

I'd have to give it a try, but I suppose we could just plug in this `RelaxType` when the geometry optimization is not requested?

**Comment by unkcpz** [comment]
I didn't know this `RelaxType` feature before, very nice! It is supported in the current aiida-quantumespresso release? If so, I think this is the best solution for this issue, and I'll try to implement it to qeapp.

**Comment by mbercx** [comment]
It is supported indeed! We should have a release for v2.X soon 😅
