### ISSUE TITLE
Bug: The filename of the "Outputs" archive must have a .zip extension.

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#267]
When the calculation is finished, there will be a `Download output` button. The format of the download file should be `zip` but the suffix is not attached.

**Comment by wengmouyi** [comment]
Hi Jason, Can you describe this bug with more detail? I used a latest version of aiidalab-qe, I can download a zip file after I click 'Download output' bottom. The name of file contains *.zip automatically. Can you show some examples when suffix is not attached?

**Comment by unkcpz** [comment]
@wengmouyi Thanks a lot for checking! I also can not reproduce the issue. I close this and if we come across it again I'll reopen it.
