### ISSUE TITLE
Fermi energy of DOS and bands are not compatible and alignment 

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#268]
**Describe the bug**
The electronic structure band structure and pdos the fermi energy are incompatible, the band structure use the fermi energy at VBM while pdos at CBM for some cases for example SiO2 from MC3D (id=7564).

**To Reproduce**
1. Submit calculation for band structure and pdos on SiO2 (MC3D id=7564)
2. Check electronic structure

**Screenshots**
![image](https://user-images.githubusercontent.com/8831685/184326326-ab31e1f9-bad9-4e8c-b45e-eb732452a67a.png)

**Version (if known)**
 - App version: [e.g. v22.08.0]

**Additional context**
Band structure fermi energy read from `work_chain_node.outputs.bands_parameters["fermi_energy"]` while dos fermi energy read from `work_chain_node.outputs.nscf_parameters["fermi_energy"]` they are not always the same.

**Comment by unkcpz** [comment]
Hi @mbercx , can you have a look at this? In which cases these two values are aligned with each other?

**Comment by unkcpz** [comment]
After having a close look at https://github.com/osscar-org/widget-bandsplot/blob/a70a3536b46aac6e0139e6b266c7caed7479d91b/widget_bandsplot/bandsplot.py#L63-L67, I think it should be fixed from widget-bandplot to accept more flexible inputs for both reset the fermi energy of bands and pdos. It is widget's responsibility to keep fermi energy alignment to each other if the results correctly correspond. 
A deep investigation is required to see how to fix this. For now, I'd say this issue is sadly blocked.

**Comment by unkcpz** [comment]
Hi @dou-du, can you check and confirm whether there is or is not a re-alignment of the bands to the fermi energy in javascript?
It seems that `band_fermienergy` using `fermi_level` passed from the input dict and use it in the javascript.

**Comment by dou-du** [comment]
> Hi @dou-du, can you check and confirm whether there is or is not a re-alignment of the bands to the fermi energy in javascript? It seems that `band_fermienergy` using `fermi_level` passed from the input dict and use it in the javascript.

https://github.com/osscar-org/widget-bandsplot/blob/9092a3d21f735fb0f5ad54a14fb1c1316d97b6b3/js/lib/bandstructure.js#L680-L686

Yes, the alignment was done in the JavaScript code as shown above, which the Fermi energy reads from the "fermi_level".

**Comment by unkcpz** [comment]
I think that is the catch. If you do the band shift you should also do that for the pdos. 
You can not make sure that the fermi energy of pdos plot and band structure plot are the same. 
So the bandsplot widget requires two fermi_levels as input for bands and dos respectively.

**Comment by dou-du** [comment]
@unkcpz 

Hi Jusong,

I rechecked the codes. Both alignments for the banstructures and DOS have already implemented inside the codes.

For the bandstructure, the code is here: (alignement for each given bandstructure json file)

https://github.com/osscar-org/widget-bandsplot/blob/f1d165b46f7a1995eeaa13166264f0f8a1bf63d0/js/lib/bandstructure.js#L684-L689

For the DOS, the code is here:

https://github.com/osscar-org/widget-bandsplot/blob/f1d165b46f7a1995eeaa13166264f0f8a1bf63d0/js/lib/bandstructure.js#L792-L798

Please have a look and double check. Cheers!
