### ISSUE TITLE
QE app: Support AiiDA core 2.0

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#272]
fixed by #271

**Comment by csadorf** [comment]
Does this require bumping of the quantum-espresso plugin dependency to 4.0 as originally mentioned [here](https://github.com/aiidalab/aiidalab-docker-stack/issues/240)?

**Comment by unkcpz** [comment]
> Does this require bumping of the quantum-espresso plugin dependency to 4.0 as originally mentioned https://github.com/aiidalab/aiidalab-docker-stack/issues/240?

Yes, it should and it's done. I add a check box to PR #271

**Comment by csadorf** [comment]
Blocked by https://github.com/aiidalab/aiidalab-widgets-base/issues/346 .
