### ISSUE TITLE
When migrate to AiiDA 2.x get exception of 'not persistent within this Session'

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#279]
I trying to migrate the qeApp to compatible with aiida 2.x but stuck with following exceptions. 
It seems when loading code from widget in notebook cause the 'session' not persistent issue?

Maybe @chrisjsewell has some clue for this?

## Attachments

<details>
<summary>Traceback</summary>

```python-traceback
/opt/conda/lib/python3.8/site-packages/aiida/storage/psql_dos/orm/utils.py in __getattr__(self, item)
     83 
     84         if self.is_saved() and self._is_mutable_model_field(item) and not self._in_transaction():
---> 85             self._ensure_model_uptodate(fields=(item,))
     86 
     87         return getattr(self._model, item)

/opt/conda/lib/python3.8/site-packages/aiida/storage/psql_dos/orm/utils.py in _ensure_model_uptodate(self, fields)
    160         :param fields: optionally refresh only these fields, if `None` all fields are refreshed.
    161         """
--> 162         self.session.expire(self._model, attribute_names=fields)
    163 
    164     def _in_transaction(self):

/opt/conda/lib/python3.8/site-packages/sqlalchemy/orm/session.py in expire(self, instance, attribute_names)
   2429                 replace_context=err,
   2430             )
-> 2431         self._expire_state(state, attribute_names)
   2432 
   2433     def _expire_state(self, state, attribute_names):

/opt/conda/lib/python3.8/site-packages/sqlalchemy/orm/session.py in _expire_state(self, state, attribute_names)
   2432 
   2433     def _expire_state(self, state, attribute_names):
-> 2434         self._validate_persistent(state)
   2435         if attribute_names:
   2436             state._expire_attributes(state.dict, attribute_names)

/opt/conda/lib/python3.8/site-packages/sqlalchemy/orm/session.py in _validate_persistent(self, state)
   3159     def _validate_persistent(self, state):
   3160         if not self.identity_map.contains_state(state):
-> 3161             raise sa_exc.InvalidRequestError(
   3162                 "Instance '%s' is not persistent within this Session"
   3163                 % state_str(state)

InvalidRequestError: Instance '<DbNode at 0x7f7614f280a0>' is not persistent within this Session
```
</details>

<details>
<summary>Environment fingerprint</summary>
<pre>eNptWF1v47gV_SuB-7oyLMlxknkbBO1DMWnTZreDoigWlETbjCmSIak4ymL-e-8XbQ3QRx9S5P0499xL_7F61zEZ71Zf6l9Wwaq8
93FcffljpWJ_NFn3eYp69eU_q922M3n1y-rP3_6y-i9snfPRu98vX6_a9f26bmHDFfpTva2r37rJ5enm5en55rsebr5Oh5t6c1O3
X7bNl01789uvjzfNpmlWP-BM1Z_UQSe63phBVb3Hy1fNerPGoxkczH5f5Sn7aJSF1c26Xm8uqyHpafAE3y3gt0mBGaNOIeqUcH0L
h17WrerwngacWGKVtk5uaJbwm_6_u990dfbx1B-Vwc_qn1fPZjjonKpOJU2r7XpL674K5qQA2mEMGYrjGwW1ZcDqsTM9fSVbXDLN
MY9WMLophMHERMiWz8YkvusqqHwkP7b8cTx411T9fm_QD7Rk8zNcdcYNxh0SrzeyHv2ZTm84HOQHWPjA2Umz66uDdjoqSA5trOm7
nKMctKWDOkh0rywnj8_u-jiHTMfx4WCAirOPzmexHB3qLHzKsd_xd1arHn27hXSib50_6SNxZktWdW_ByhF1s24Jij5bE-YFSbpp
DEBc_G4DZtZ1jbc9wtH60bscvS0n1HhJjwvZe5uISA3Z1l_8bISRvY7ZcIw3ZHF9iyiHHW655V37w_si18CeOOgsLm0ESTpXDlih
rPlkO8sdRz0at_c_udOb2E-JTb7jU62hwAF7KCz0G-rL7c2h2huraTPHlNdSMM7RVUh_SmTvrY9qVJIQcsa7QVEQak4kAZWUcnVU
brDAowVz-U7fvYqHO8L8yeh-ylkzb-7YSOSEP0QVjuhdC85xpOfeFss4Co8kR8wnYCMSaFA96Bedxm4NupsOFCZEWkJAYISrt-
gkYfsp6eFjtBJPBkE2IL-
sayX0g0mnChwBkUyZlaqEEJaAYh0hLbk4uBSKkcBwPnayZ9NzZTbgGgZUQ6lrl6Vim_UtWapHZWz1DtkfLrXFZ8BeiJI3LnO-MT7
6o9cBjT1EPwVWovUm9vewtlcpq2DYVj4codfkXUIuKXZwR4cjMawn4rQiMnsohyvzW3Z3P3GbwITcU_lS0t7NZ_GtJkxrZ4natSi
qGcB-s58XrprBKS4H_DEGHzGS1aizAt9_4tp1FUTdT7HH3gGZbPjbMOMHIrtsLlwbfMo1L590dNqS8EItCig5AgayWAmEwjZlY9N
CtHAJfBJEvr_edyfsuYKV_sjaDXpYJPBVD6ZEDn__1bhX1bCwUoxeCaiyGfXi7lffMcFqYSNmkHgg8tAKFvWeP5Pflyy35aQJ3NC
xgrKHZHA0IMLLFSb3FqutvuKLpkbHcZZP5nzV1p0Aydt3KW0WcqviCVQCdC0WZd0QnIG8HgpT2j6eaPWHGS7SvNngocjKi2zV3DK
e1MkvAvsEVwz-zMPJ9gJN4UXt9eL4UWVsERzNVlh4BSvjQMHkIl6D4p4EuSdvRiiKucg89IMdYVFXoECxVAuklxk1hpGru1g6pkP
gvlaLwo2TzWYwPaeDkzdO7hR1kpTTrjnMTCmcuKT-yUTXgcxCxLmNcDG7Dmc7xRBb4nTKFfVtw5G7JVF3OuMc80FBumfoYN-
NPkue6QrIknbvItd0ms-6AyUnm7dMIQeNlSW3ackLb_Ulb1uMkwelGtVwUY_NArtyUhpogzdzc-
Gu0nBKAkxIOavOaumkGwLHt8C1IL-hNZXxqBXA92AOZCmJ_7wRupwhMjWlwyBXvaScv81HYEcj599ddAUXUiACb9YP8m0-FhaUWT
J00nW4xwf9Ad9kqjKOQTikSeqd9kNPtjrBKKCltjAtz8ZamskepJifjZNhh5MeTOCJhHlVJnyZE1Fz6XCk-
kz2iMVW8gbXi_9-ZvclREDu3o-jyRwkLqUQPej0UU_pmrkN0r4shlxhIE4mFybRYQmVVa6nrWnufTg0FU-BdAUPmSHPcA4IfVqMO
2HuQDbY2q0gvTJR1IAdeJ4fzf6f3ynCkn64JKksbVuQiyZB2MkUaCLQonj2fqBoPc8HbNEcQBGuMENlQYsoVIW9tPNpfvnHN6FCS
8jf1KNdcm3-e9Du5eVbSRODaAYzHKP0QBggKV-Cyt0izGmEckqiHTVd8QLimKQweRN1MOiGWgKNZd1cV5KdDtyFd4WesACt7TUt6
2fO_rVXY1g8urADqlnmHPnws2g1O_zvr0_fRHPYmE962zSl_8CrqRRH8T9qauyqKPLunsC3CfSK9zXsfsEqmsglzrfLhdGLsHL84
75vH-7v5P1Fx05q1HY9K5n4YGCmxC_wdV9muYY6Gi9VuFSVAXiDI8Q9Gp96A_yu4GESXeFkw7hIIddY0voUSiN4WN8B9ALDQfNrV
Om4eNbB6D-FEqFdiVo6QoSmyQySeaRIMh_cHXgqS-FwGRF2FBXg4leL_X8urZj2ZRVRPnWpVrI2R2g_FcarbR-42BCei55LyYPoT
ti1RRrpnQAkxeF7pqYn23SEZ4qSl7m8fDJk6PI03Qn0kavJGRzNB3kmIwxkVEOAIPTZymxE233JGvdI_G0WvR1mZbl0x-tvw0gKs
GOdAPKabHmAuRWaEwYyo9NisIPfUI6__9Rst_LB5PChB2_-bHQS4-4IN-gEDqHYJuryj8MU9sD4CoexBWOnaK8vvEWTAhyy2LKU7
fj9-S8F9TEvusm7ATJAD6R-3JD647dnlfvj4A8lRNgCzj3MbBLzhm4-645edjJaNAxpB8bLXwCo-njvdx1Pn3o6yCOIdh615hS0L
DY8EVYd9NZ0eXo3VGqyFHQ0HoebS7_muMgs6bpLlGmRG9kZHhTycuCL4YV2GWUJRIdnYPLirflpQij_Ta1-_PgfdndQCQ==</pre>
</details>

**By submitting this issue I confirm that I am aware that this information can
potentially be used to determine what kind of calculation was performed at the
time of error.**

**Comment by chrisjsewell** [comment]
Heya, it would be helpful if you could extract out a "minimal working example" of code that can reproduce the error

**Comment by unkcpz** [comment]
I tried, but really hard to spot where cause the issue. I'll look into it more carefully and report back.

**Comment by chrisjsewell** [comment]
Yeh ideally, I would be able to launch e.g. https://hub.docker.com/layers/aiidateam/aiida-core/2.0.3/images/sha256-e4a119f0288c4e9c73a9f3f332eb1af5aa4b1163beeb1545a8f2d4a8d4838337?context=explore,
then run a bunch of verdi commands / python code, and reproduce the bug.
Otherwise it is going to be difficult to debug 😬

**Comment by unkcpz** [comment]
The orm entity is tight to the widget class as traitlets which will be not accessible after the database session is closed.
This should be fixed by https://github.com/aiidalab/aiidalab-widgets-base/pull/354. But it requires changing the widget API.

**Comment by unkcpz** [comment]
close by #271
