### ISSUE TITLE
Warning: 2D structure detected. Note that currently only three-dimensional structures are supported.

### ISSUE THREAD

**Issue by superstar54** [aiidalab/aiidalab-qe#302]
**Describe the bug**
The qe-app shows the wrong warning message.

**To Reproduce**
1. Go to qe-app
2. Load a Silicon (diamond) from the examples.
3. Select one atom,
4. In the `Edit structure` panel, move the atoms

**Expected behavior**
The page shows this warning: ` Warning: 2D structure detected. Note that currently only three-dimensional structures are supported.`

**Version (if known)**
- latest version of 'aiidalab/aiidalab-docker-stack:latest'

**Comment by superstar54** [comment]
Thanks @mbercx . Yes, the running is good. But I think it is better to fix this. Otherwise, a user who doesn't know the detail of aiidalab-qe,  may get confused about the warning.

**Comment by AndresOrtegaGuerrero** [comment]
#479  fixes this
