### ISSUE TITLE
Output follower show nothing

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#325]
**To Reproduce**
1. submit a calculation
2. go to check the `PwCalculation` note from node tree.
3. Nothing has update in the Output follower.

**Screenshots**
![image](https://user-images.githubusercontent.com/8831685/204782317-cbb2bf17-09cb-4317-8b28-d25d9a7ed8ca.png)

**Version (if known)**
 - App version: [e.g. v22.11.2]

**Additional context**

**Comment by unkcpz** [comment]
@danielhollas do you have the same issue of your app with the new image?

**Comment by danielhollas** [comment]
I needed to update the code to use uuid instead of AiiDA Node in the traitlet, take a look at https://github.com/ispg-group/aiidalab-ispg/pull/80/files#diff-7de888163d19a15c2c2a188fb8397b5a6b99e627e73b33bdd70188d3bb87b1eb

But I thought you already made this change...

**Comment by danielhollas** [comment]
btw: Did you check that the calculation is actually running? Sometimes empty output just indicates some other issue.

**Comment by unkcpz** [comment]
Yes, I guess we use the same code. I'll check it carefully. 

> btw: Did you check that the calculation is actually running? Sometimes empty output just indicates some other issue.

Yes, the calculation is running.
