### ISSUE TITLE
New workflow from the workflow monitor bar

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#326]
## Automated report

When a workchain is running, create a new calculation by using the workflow monitor bar.

## Additional comments (optional):

_Example: I submitted a band structure calculation for Silica._

## Attachments

<details>
<summary>Traceback</summary>

```python-traceback
/opt/conda/lib/python3.9/site-packages/traitlets/traitlets.py in _notify_trait(self, name, old_value, new_value)
   1372 
   1373     def _notify_trait(self, name, old_value, new_value):
-> 1374         self.notify_change(
   1375             Bunch(
   1376                 name=name,

/opt/conda/lib/python3.9/site-packages/ipywidgets/widgets/widget.py in notify_change(self, change)
    684                 # Send new state to front-end
    685                 self.send_state(key=name)
--> 686         super(Widget, self).notify_change(change)
    687 
    688     def __repr__(self):

/opt/conda/lib/python3.9/site-packages/traitlets/traitlets.py in notify_change(self, change)
   1384     def notify_change(self, change):
   1385         """Notify observers of a change event"""
-> 1386         return self._notify_observers(change)
   1387 
   1388     def _notify_observers(self, event):

/opt/conda/lib/python3.9/site-packages/traitlets/traitlets.py in _notify_observers(self, event)
   1429                 c = getattr(self, c.name)
   1430 
-> 1431             c(event)
   1432 
   1433     def _add_notifiers(self, handler, name, type):

~/.local/lib/python3.9/site-packages/aiidalab_widgets_base/wizard.py in _update_step_state(self, _)
    188             self._update_titles()
    189             self._update_buttons()
--> 190             self._consider_auto_advance()
    191 
    192     @traitlets.observe("selected_index")

~/.local/lib/python3.9/site-packages/aiidalab_widgets_base/wizard.py in _consider_auto_advance(self, _)
    175         with self.hold_trait_notifications():
    176             index = self.accordion.selected_index
--> 177             last_step_selected = index + 1 == len(self.accordion.children)
    178             selected_widget = self.accordion.children[index]
    179             if (

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```
</details>

<details>
<summary>Environment fingerprint</summary>
<pre>eNptWF1v47gV_SuB-7oyJNlx4nmbBujDYqZNm9kOiqIIKImWOaZIhqTiKIv573u_ZCvFPvqQIu_Huede-vfVq47JeLf6VP2yClbl
g4_D6tPvKxXbo8m6zWPUq0__Xe22jcmrX1ar_8G-KR-9e758utqs9-tqA6tX6C91uS1-a0aXx5unr483f4vm5vPY39S7m2r_qS4_
1dXNb98ebuqyrlc_4UzVnlSvE91tTKeK1uPNq3pdrWs4msGQ9Nh5gMv1_bq8wC-jgosGnULUKeH6Fj67rFvV4Elw1Eew0NbRWYsr
ED76Qf_5By9XvP6IF2cfT-1RGffnO86m63VORaMSu1WuS8U7fBHMSQG4A6cqhuLwQoHdMGD10JgWkGre4pKpj3mwgpGVbjKevtrx
nhA6ExPt2K63jAy-08v4YZ5fdRFUPhK85U9jzz_rHbsRe-_qoj0cDBpfgV3lR7hojOuM6xOv17xOvm7WGA_6mbM_aZckAPeETa4t
eu10VNlHMraib3Mm2_FbOuyvqtGWGVGukW0NcKZV1rKhtAeh4GNO68Po2uy9TYWNY9Gq9qjp7B0FomnjFDLbRg42Wo3ZHEab_Bi2
TKCKjG6sho8BuQWLGTDupNnSW_wNLh3Jri2bFX22Jkxk1h2Z9YDXP3iXo2drK3ACryW7yEy6sibj2oXr7FarIxhHoYd6gWqrtzMq
91R0teQHDL8lU4GPMelcOOCTsuadrMZ48qIejDt4OWHPN5nYjomPvKPItNa0JwDu5zvwN1SnO5i-OBjLbNrx17SWgnGOrkK7KJmt
tz6qQQnFbglynWIn5WoEChGC4qhcB4HuyZ3LBrjTNz8kGTvGsh8j-VDNGObW91GFI8IbYDrHdWrtbBZT6oGUjPmzX2_Q3U61oHtC
lZKArFqrUtIcFiRtp5uxlzt3FJVOg14JgW8lwJ0-jEl3b4MVKjAIGgUZZpmcud2ZdCrAMxDclFn45ph2LoXZTOQDHTLas2mlQsv1
Le7ToBHaZSnken1LdulBGVu8QvK7S3lx7cJeiJM3LrNfGCH91uqApvURykBCygu6hfqQdLB7ByhnFQwHhdUEoR_Ju4TcUuwfCwgS
xXoi0kak52BNfhaV30h0DpDOazlsZOPIXQjzdk-nUW5fzfscgIowrZ3VWSxE54_joNwhGg1UomSVdJ7pnKI70TMzoF5Y0xSDzgqT
PRf_x1VoLMCzlkhwC2nA86H4QAgcqdIOPS0ZHIKVkqoZkPTdrTebeQ9CKHsQVZsWCoZL4Ikg8r00Dzri7v_AQr9lcFB3i9SYnDrl
eg1ZTIse-kN3Zg4jbvvVuB_QgzAUssGDuDV0EFuDybwVX27lN3FGlGQjWNQHtlh-
XwiwmQ8awS8dn0EhgHgcCz5xXmAiXGRX8CLp-CpiW-0_rGRiPJBYhGZxzXFs6O5yCfIUAFmnEr6CRZh6rJy0iPl19fliQI2q-nGx
uCZmDv3JnK_avxMgeTs7wY3YqngCqQNxjnM_KAnOUILQoVvpkHgiZGRQQ6NEb9hR6_sxjguZ-KpOXhKHSaEvFvu_woWdPzuJQCXQ
GJ7UQS8uG1QOFvtXI4NE_QEsjANRllok9waT8ujmI9C3AWp4uraqPUFRFyCrca5t4N-W7BrCwIJVibQNqccWsNCeYbTZdKbNVGXM
MadygsKkkzh0riGRpiFpbjGICd3mTgyQd5ALpiBf6RqcelWmyubRyemUCxpNDEf1lpx1OuOY90be3hOPXG9fjT4L3TD0zmfdeH8i
c7fc52esSEczLPjqxkHSWnM5eBhDjnP02TwPijyo7iKA5QIrLg5KtCsMN_dQVuuapTDACJmzaqyWsbIkcNBWSagFeAlc2PIbWnKS
ANQC-BbEHHI547wRurshBtYzmZHe86jOJuTjnP955A76LWjK7Fa6QujTKIVIH8FAYXWCOUZLFjFKj8ZajzHfi6GPRrJccf6CCTxa
MIXCqUedfUYRh0p8dmrQ0gppPCF2T9y6OTHBSmbAEC7sEOFVkI96TMWCVdX2shhyge6dTJ7JQCsJb6ajuR2ENLU-9DWFas9OCoQz
tCI9u6zkCY6GrpMWHA7QDQsNPX0hWGFqQDoY4Mp6nB7M4V_fKbRcDgFuSSqLaGwYuYgQnFMxNEZL1bHlITJM0EuyvD4qrr_Hq2RC
viUH06_fv8noQWZOUFPQ4WZyViQFj9PX6emfX6SnbAj5u3qwSzJN_wjaPT19WU7_YUJLmdMYXOL5BEjKl1xwV3ucnmDQYHbeiQfU
baG5a0kGVm99XcGWVYCk9hKJcv7M_2jVEBYFi91ZMS94fgDgnT2sxJv_fP76hfIt1Jje6S2HaSEA3opzGdRSd1G_jKA4DNXsxoxd
3i4Yr91yYfCikzLXxEO72d_fCbFRnOKIFb6elIygONJXH_F1y2qDRNpdlgpcKuYRvcTOd49XpNYAvwt4EkU3k61mXHSMc5q0PoVZ
2PfrO4CeYEipv0WVjosnKzxOxjBHYzeHLB1B28fRdCJNFYHmjZ3lfpecgceOXwy0-HJLRr9qEbB6HXzK9Gno57EGvsZSAAZ-
tjijTHNTpn0w6Z8KmQFhrF4LGFE7ZSRjbUs5QkMqMOKbzZ5rE-FplnOZYkBxR2zqIoMkNsBXfGNM8qZiKMJTTMk_G-JhPkatugDB
abOVIY1w46Y2pXoxdGQ_J5jLE3-bBZMxwu_LQQOeAnIdd_j80g2kFDvOAJDcZMuTDWaFvpngXdc_07iJ__IkkRZcg8c29FQFKmxo
QkZbMSBjOADZqb4WEzEIzPVJKgnYMA552nA_3HHa_61gAp8WLeOscnvsfD_7i0V4bmEQkz8wakrwWTf05pTRrGZIOxiu5E-KOb8A
JygkeCVfZL0SHn7X8fSux34xQp-
PWnOoN6wtPAEWDTTGhG1ETi6vS0FH43F-uXTfcrGcXHOJ6OK_mzO8cOQpw7bAK_IyVBO9MGCTinbxp9C7CUH-
jitXP3_-AaDQmXU=</pre>
</details>

**By submitting this issue I confirm that I am aware that this information can
potentially be used to determine what kind of calculation was performed at the
time of error.**

**Comment by danielhollas** [comment]
This looks like the same bug I reported in AWB https://github.com/aiidalab/aiidalab-widgets-base/issues/343

**Comment by unkcpz** [comment]
Fixed in https://github.com/aiidalab/aiidalab-widgets-base/pull/466
