### ISSUE TITLE
Adding a total charge of the system option

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [aiidalab/aiidalab-qe#338]
Hello, I think it could be useful for the app to have an option where you can select the total charge of the system.
This could be useful if the user is trying to study a system with a different charge state. The issue of charge can also be important if by using the widget of structure, the modifications lead to a charging system( on purpose).

I was thinking of something like this , where the options are limited from -2, -1, 0 , 1 and 2 charge
![Screenshot 2023-01-12 at 15 53 52](https://user-images.githubusercontent.com/34098967/212100011-e2041e06-a874-4dbe-a1cc-e382a4cab5b7.png)

**Comment by unkcpz** [comment]
@AndresOrtegaGuerrero thanks! How does this parameter influences the QE input? Can you post the pw.in with this setting? 
I think for all such kinds of change, we need first to have workflow supported in aiida-quantumespresso and then we wrapping the workflow in the QeApp.

**Comment by AndresOrtegaGuerrero** [comment]
@unkcpz  I did it like this:

add an extra variable name tot_charge, so it can be also part of the GUI as an input
I can do a PR of my implementation if you want 

```
  @classmethod
    def get_builder_from_protocol(
        cls,
        structure,
        pw_code,
        dos_code=None,
        projwfc_code=None,
        protocol=None,
        overrides=None,
        relax_type=RelaxType.NONE,
        pseudo_family=None,
        tot_charge=0,
        **kwargs,
    ):
```
and then just use this variable to modify the input

`relax.base.pw.parameters["SYSTEM"]["tot_charge"] = tot_charge #add_the_charge`
`bands.scf.pw.parameters["SYSTEM"]["tot_charge"] = tot_charge`
`bands.bands.pw.parameters["SYSTEM"]["tot_charge"] = tot_charge #add_the_charge`
`pdos.scf.pw.parameters["SYSTEM"]["tot_charge"] = tot_charge #add_the_charge`
`pdos.nscf.pw.parameters["SYSTEM"]["tot_charge"] = tot_charge`

**Comment by unkcpz** [comment]
@AndresOrtegaGuerrero thanks a lot for the details!
However, I think we'd better hold on for the moment, this definitely introduces more complicity to the workchain. The `get_builder_from_protocol` function of QeAppWorkChain is already quite unmaintainable. 
For the QeApp, in design, it is not enough just add one more parameter to support new flexibility, but in my understanding, it should also showing in the "result" tab and "workflow information" tab to show user the difference with the workflow without having this parameter set (in your case, how user distinguish is workchain is running with your new parameters on or off?).

But anyway, I think this is a super good example for us to dig more about how to adapt the new design to decouple the workchain into small parts. 

It brings up a new question, whether for QeApp we just wrapper the aiida-quantumespresso workchains without doing anything more? The downside is it will limit the flexibility for extending QeApp to  do more than simple tasks.
Or we want to maintain some new workchain inside this repo with even add more logic/override to the workchain?

**Comment by AndresOrtegaGuerrero** [comment]
@unkcpz  The other approach could be just to get the builder from the QeWorkChain, and then assign the parameter directly using `builder.base.pw` , without modifying the work chain. I agree the best is to decided how will be adding settings to the app.
