### ISSUE TITLE
The QeApp has aiida2.x supported version released but not supported by the current materials cloud aiidalab deployment

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#339]
From `22.11.1` , QeApp drop the support of aiida1.x. However, not all server is deployed with new aiidalab image to support AiiDA2.x. Especially the Materials Cloud deployment is not move to aiida2.x yet. It lead to the server issue that the QeApp is collapse when the latest version is installed in the Materials Cloud deployment. 

Ways proposed to fix this:
-  (hotfix):  retag the new releases after 22.11.0 as alpha version. This will prevent Materials Cloud AiiDAlab from installing the latest version.
- Hide all versions that has dependencies conflicts, this required changes on `aiidalab`.

**Comment by danielhollas** [comment]
@unkcpz @yakutovicha I think we need a general solution to this, we're run into the same issue with other apps, notably AWB. So I think this needs to be fixed at the level of the `aiidalab` installer, and we probably need to backport the fix to the old Docker stack image, otherwise once we release AWB 2.0 we will break people's containers.

**Comment by unkcpz** [comment]
When I test with @yakutovicha, we find in the materials cloud deployment, where the aiida-core==1.x, the installer will fail and the new version will not be installed. I can not reproduce the issue that the version incompatible app installed and break everything (@danielhollas if you have an example that will break the whole environment, then this issue will become more urgent).
But sure there are still a problems with not having aiidalab tool support the version compatible pre-check. 
- In the home page, it will showing the `update available`.
- User can find the new but incompatible version from app installer manager.

One way is implement the check before the app is installed, and hide the incompatible version. Or when the user selects the incompatible version, a warning prompt ask for `danger` confirm.

@danielhollas it will be helpful if you can provide more details on how you suffer from this issue and we try to find a general way.

**Comment by danielhollas** [comment]
One thing I think you should test to see how critical this is. Try having the existing old docker stack and old QeApp version, and than trigger the update to the incompatible version. What will happen? I suspect Aiidalab will try to upgrade the app, and fail in the middle of the upgrade. Is the installer clever enough to roll back to the previous working version? Perhaps it is and I am paranoid, but these things should be checked.

**Comment by unkcpz** [comment]
>  I suspect Aiidalab will try to upgrade the app, and fail in the middle of the upgrade. Is the installer clever enough to roll back to the previous working version?

Indeed, we did the test on materials cloud deployment. First, we have aiidalab-qe==22.11.0 installed, which is the final version having aiida-core 1.x supported. Then we try to install aiidalab-qe==22.12.1 and it fail in the middle of the process. Nothing actually happened. But as I said, in the home page, there is a blue `update available` showing.

**Comment by danielhollas** [comment]
> One way is implement the check before the app is installed, and hide the incompatible version. Or when the user selects the incompatible version, a warning prompt ask for danger confirm.

I think the general solution to this (e.g. find if all dependencies are compatible) is difficult without actually running the pip resolver itself. But if we focus only on the current migration, we should be able to just check the "aiida-core" requirements and decide based on that. I think this is essentially what should be done as part of the https://github.com/aiidalab/aiidalab/issues/318

**Comment by yakutovicha** [comment]
> I think this is essentially what should be done as part of the [aiidalab/aiidalab#318](https://github.com/aiidalab/aiidalab/issues/318)

Yes, indeed. I will also assign myself to https://github.com/aiidalab/aiidalab/issues/318 and will work on it tomorrow.

**Comment by unkcpz** [comment]
This is closed with https://github.com/aiidalab/aiidalab/issues/318
