### ISSUE TITLE
Band/PDOS zoom changes when delesecting some PDOS channel

### ISSUE THREAD

**Issue by giovannipizzi** [aiidalab/aiidalab-qe#351]
**Describe the bug**
When I deselect/hide some PDOS channel, by clicking on them, very often the zoom changes.

**To Reproduce**
1. Open a finished workflow, wait for the bands to load
2. Click on one of the spin channels. Not always, but very often the zoom changes (see screenshots).

**Expected behavior**
The zoom should not change but remain the current one.

**Screenshots**
Before clicking:
![before](https://user-images.githubusercontent.com/16132028/219008740-2c19652c-3a62-476b-a772-6c0f46e1ef2a.png)

After clicking to disable Sn:
![after](https://user-images.githubusercontent.com/16132028/219008755-94b53fe5-43b0-4c14-9353-b2c4daf3ddcb.png)

**Version (if known)**
 - App version: [e.g. v23.02.0]

**Comment by dou-du** [comment]
I think I understood the issue. When you click the PDOS, there is a small motion of the mouse, which trigges the drag to zoom function. This is a inner issue from "chartjs-plugin-zoom", which is not totally fixed yet.

https://github.com/chartjs/chartjs-plugin-zoom/issues/256

**Comment by unkcpz** [comment]
We are not able to address this issue in the next release, I'll move it to the milestone `v24.4.0`

**Comment by unkcpz** [comment]
The widget will be replaced by #581, and will be released in `v24.04.0`.
