### ISSUE TITLE
Bug report: Application crashed with KeyError while looking at the tree view

### ISSUE THREAD

**Issue by giovannipizzi** [aiidalab/aiidalab-qe#353]
## Automated report

_This issue was created with the app's automated bug reporting feature.
Attached to this issue is the full traceback as well as an environment
fingerprint that contains information about the operating system as well as all
installed libraries._

## Additional comments (optional):
I was clicking on the Tree view to see the sub-sub-workflow and this happened.

## Attachments

<details>
<summary>Traceback</summary>

```python-traceback
KeyError                                  Traceback (most recent call last)
~/apps/quantum-espresso/aiidalab_qe/widgets.py in _observe_node(self, change)
    382                 clear_output()
    383                 if change["new"]:
--> 384                     display(viewer(change["new"]))
    385 
    386 

~/.local/lib/python3.9/site-packages/aiidalab_widgets_base/viewers.py in viewer(obj, downloadable, **kwargs)
     82         raise
     83     else:
---> 84         return _viewer(obj, downloadable=downloadable, **kwargs)
     85 
     86 

~/apps/quantum-espresso/aiidalab_qe/node_view.py in __init__(self, node, **kwargs)
    508     def __init__(self, node, **kwargs):
    509         if node.process_label != "QeAppWorkChain":
--> 510             raise KeyError(str(node.node_type))
    511 
    512         self.node = node

KeyError: 'process.workflow.workchain.WorkChainNode.'
```
</details>

<details>
<summary>Environment fingerprint</summary>
<pre>eNptWF1v47gV_SuB-7oyLMl24nmbDtCHxUybNrMdFEURUBItM6ZIRqSSKIv5771ftJXFPvqQIu_Huede-
vfVix6j8W71qfxlFaxKRz8Oq0-_r9TYnkzSbZpGvfr039V-25i0-mW1-h_sm9PJu8fLp6t6fViXNaxeob9Um23xWzO5NN08fLu_-
dtobj5P_U21vykPn6rNp6q8-e37l5tqU1Wrn3Cmas-q15HuNqZTRevx5lW1rtYlHM1giHrqPMDlerPeXODnScFFg45h1DHi-hY-u
6xb1eBJcFD5ASy0RVs363JdLeGTH_Sff_BMeP2HwwEuXv14bk_KuD_d8Gq6XqdYNCqyU2B9w275IpizAnC_vhNPIQfPFNaaAauHx
rTktWxx0VSnNFjB6C43G09f7XlPCJ0ZI-3YrreMDL7T5LF8g1l-0UVQ6UTwlgMx9vyz2uff3lVFezwaNL4EuzYf4aIxrjOuj7wu3
pOvEAvJYEzJn7WLEoA7wmbXFr12elTJj2RsSd-mRLbjt3TYX1WjLX1ZbtbItQYY0ypr2VDag1DwY4rr4-Ta5L2NhR2nolXtSdPZe
wpE045zSGwbOdhoNSVznGz0U9gSfSDzaHRjNXwMyA4sZsC4s2ZLd_gbXDqRXVs2a_TJmjCTWbdk1he8_ot3afRsbYnEggWyi8wUx
m4JvLrObrV6BOMo9BuMR7W-zajcU9LVkh8wfEemAh3HqFPhgE_KmneyGuPJi3ow7ujlhAPfZMZ2inwkM6S1pj0DcJfvwN9Qm-5o-
uJoLLNpf91bxGCco6vQLkpm660f1aCEYjuCXKfYSbkagUJkoDgp10Gge3LnsgHu9M2TJOOOseSnkXxARaC4YG59P6pwQrg-iFK0c
2uzWUypTrUgccILBpJqrYpRcwzwik43Uy8X7CkEnQZpErbuJJqdPk5Rd2-DlbwzCHIE6WRFzETuTDwX4AZoa0yscTmAnYusrbSdi
6yb7KtppRxZpzTogXZJirZa78gsPShjixdIdHcpJdYPPQzAgjbfVd8Rz-AEiJQ3LrGzhL21OqC9_QiFwFwiK_SbbqFCJCHs8xEKW
gXD9OEYI_QUvYvILsVOs4QgVawnKtWS0KM16VGsqiVkR0jotSBq5uBx4i7ErERfKbsv5p2jwoXZj1o7q5NYiNtO06DccTQayEQZZ
CtN5xTdiS6bARXDmqaAIClkQC7_j6vQWIBpLTFjB4WJ50P5gRQ40qU9erphcAhWiqpiQHJ6u67rvAchFD6Iqo0LDcMl8EQQ-V7aB
x1x-wew0G8JHNTdIjUmxU65XkMWo1APP3rSnclhxG2_GvekKgqFbIDc7cT0nfwmioh01IKN-sgGyu9LvnPje5rADT0-giQAz9h1P
jEvcN4vOit4EfX4IupaHj6sJKI9cFaUZXHNaWro7s0S5KYPSaYyvoJFmHssn7gI8XX18WJAhTL6cbG45iFH-mxer2J_K0D0NjvBn
deq8QzaBmo85gawIThBxUFLbqUl4olAtkENjRLNYUexdC5qW7LR1vfTOC3k45s682jEiaJTFmd8AyM6_-okKqVAU3hQR70wYFApW
GxijUwT9QewMA6UWSxZ73HNxDS5fAT6O0AZz7lfHdYHgkZdgNyOubyBgluyawhFlpF6QyQZwsDaVsrwN8QeO4OoPN0w2WQ60yYqP
cacShGqlc7mALuG5Jxmp9x5EBNS5gYNkHeQMSYqX-kaHIVVonLnicrpmAqaWAzHeUfuO51w-HtjCiLQ2xejX4WSGD3nk268P5OxE
PpqgRXxZIYFp900SOorTpKH2eSUs8HGeRDpQXV62akzVlzck-iXGH5urCzgFatjgLkyJdVYLbPmhsBBW7UYsAF4Dot-
FKAzqyju1wL4FsgJuc04b4SWb4iRVSY8loCX-ZO_TafMhzyFB_0WNOV1K1Nq6OMkxUofwZRhdYThRksOMa33xlqPMT-smVb3RnJc
cvaCCTxvMFnCuUfpfURdh2p9dGrQuWfSpcj2mVu8eG4lM9SIyZIRHgrppKdYLDhVctpwMaQC3TublMlAKxFvpqO5Q4Q4tz70FYXq
wEcLhIO1Is27rKQZjoZGFBcMDtAgCw3NfyFqYW5AXhiQkMxfzPFfPyi0XAwBbokqiYjUjFyECs4pGZpGS7Wx5ckyzNBekjxJSu4D
91dZrXLI7udff3yXGYXMnKGioOldyUkX3M_f5od_fpXGUxPyd_XFLtk0_yNo9_DwlZ9Xws0ZTWVSI0ZEnwGJ6ZIM7nT38wMoKNPz
VlygDgwNX0s2KqBbdV3BvlaAxvYSik3-zD-1agiLisWOrZgYPFMA8M4uluLNfz5_-8pKRcvv9L7DrNCh8HzMVVCJa6N-nkBuGKrY
iYxd3jMYrbvlwuBFJGXSGY9tfbi7FV7T1gkLfD0rmVTLW07BAl-3LDbIo_1lqcClIo_tG2yOd3hFbE3uVHxn1PocsnwfqCc-
wHxSfR9VPC3eq_AymUJ2e7-TjhRPoODTZDqRIHonRfPGN3D8ojPw0vHiFSEwrUajX7QIVbUOPib6NPTsDX2NlAeifbY4r8y5QdM-
mPzPhYx_0IXWAo6okTKNyV1phLZTYGjr-sA1iPCcZVsmGlDWCRu8yB2JCtAS3xzzokWBasI7THU-axWBxs1tjNVi0Eg-Z4zLDX-
bBTExku_L4QLeAHIsT-DpuRuo8vccaeCsSZanmZ1oJkgLVNMjTZT4R04UqcC1CQuC9nJFwgsbOqYClTU0FOMMiYGYwhHYXMjuPAS
DgFzfoRL4mnHIT839bs_p_reCoXtetIRXldpT5_vsP9bYawvDmPxrUVFiX3VDD00ZzyqGtIMBS_6ZyHkFOEKl4KMoy3Yp_Puhx_O
7nvrF1Px60ppDX7N08BRYNND4IrYJOXlzWXoMejQep5NLdy0Xy9E1lwgv_rB5hUeNvF7YFnhNXgZrohUGbFZj_tcHjXs3IVzeVD9
__h_-z5Uk</pre>
</details>

**By submitting this issue I confirm that I am aware that this information can
potentially be used to determine what kind of calculation was performed at the
time of error.**

**Comment by unkcpz** [comment]
This is duplicated with https://github.com/aiidalab/aiidalab-qe/issues/344 and the fixing is in process.
