### ISSUE TITLE
status tab: indicate progress of workchain

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab-qe#36]
![image](https://user-images.githubusercontent.com/1053245/101023205-b8ecc280-3572-11eb-9eef-a2bacf2afd30.png)

 1. The Calculation state switches between "Waiting" and "Running"
    It actually shows "Waiting" while QE is running and "Running" in between. I know where this comes from, but this is confusing
 3. The Process shown in the text field stays the same throughout the whole workflow. I.e. one does not see e.g. the name of the calcjob whose output is shown below.
 2. The progress bar is stuck at the same progress for most of the run.

Point 1 is relatively easy to fix - simply include the "process status" as well (which would be something like "monitoring scheduler: job state RUNNING")

For point 2, I guess in other use cases this field is not greyed out and one can use it to select the process (?) - if yes, one can keep it like this, but instead of showing the active process in that field one could e.g. show the currently active process as part of the message shown on top of the progress bar where it currently just says Waiting/Finished.

Finally, it's very rare to use the UUID to interact with processes in practice. I therefore propose to show
`pk: 2170 aiida.workflows:quantumespresso.pw.bands`
(and add the uuid in brackets at the end if you prefer to keep it)

For 3. @csadorf already mentioned that a progress bar might not be the best way of indicating progress.
What one would probably want to see is something like the output of `verdi process status`
```
PwBandsWorkChain<2170> Finished [0] [7:results]
    ├── seekpath_structure_analysis<2171> Finished [0]
    ├── PwBaseWorkChain<2178> Finished [0] [7:results]
    │   ├── create_kpoints_from_distance<2180> Finished [0]
    │   ├── PwCalculation<2184> Finished [0]
    │   └── PwCalculation<2192> Finished [0]
    └── PwBaseWorkChain<2200> Finished [0] [7:results]
        └── PwCalculation<2203> Finished [0]
```
A first prototype could be to include the output of `verdi status` as text below the progress bar and simply update it whenever the progress bar itself is updated.
One could later make a more interactive version out of it (with folding / links /...).

**Comment by csadorf** [comment]
This is at least partially addressed by the current tree status view.
