### ISSUE TITLE
Bug report: Application crashed with KeyError

### ISSUE THREAD

**Issue by mbercx** [aiidalab/aiidalab-qe#361]
## Automated report

_This issue was created with the app's automated bug reporting feature.
Attached to this issue is the full traceback as well as an environment
fingerprint that contains information about the operating system as well as all
installed libraries._

## Additional comments (optional):

This happened when trying to reselect the `QeAppWorkChain` in the tree, since the outputs weren't showing.

## Attachments

<details>
<summary>Traceback</summary>

```python-traceback
KeyError                                  Traceback (most recent call last)
~/apps/quantum-espresso/aiidalab_qe/widgets.py in _observe_node(self, change)
    382                 clear_output()
    383                 if change["new"]:
--> 384                     display(viewer(change["new"]))
    385 
    386 

~/.local/lib/python3.9/site-packages/aiidalab_widgets_base/viewers.py in viewer(obj, downloadable, **kwargs)
     82         raise
     83     else:
---> 84         return _viewer(obj, downloadable=downloadable, **kwargs)
     85 
     86 

~/apps/quantum-espresso/aiidalab_qe/node_view.py in __init__(self, node, **kwargs)
    508     def __init__(self, node, **kwargs):
    509         if node.process_label != "QeAppWorkChain":
--> 510             raise KeyError(str(node.node_type))
    511 
    512         self.node = node

KeyError: 'process.workflow.workchain.WorkChainNode.'
```
</details>

<details>
<summary>Environment fingerprint</summary>
<pre>eNptWF1v47gV_SuB-7oSLMl24rxNA_RhMdOmzWwHRVEElETLjCWSEak4ymL-e-8XbaXdRx9S5P0499xL_75602Mwzq7ui19Wvlfx
4MZhdf_7So3N0UTdxGnUq_t_r3ab2sTVL6vVf2DfHI_OPl8-XVX5Pi8qWL1CfyrXm-y3erJxunn69njzl9HcfJm6m3J3U-zvy_V9
Wdz89v3hplyX5eonnKmak-p0oLuNaVXWOLx5VeZlXsDRDPqgp9YBXOTrfH2BXycFFw06-FGHgOsb-
Oyy3qsaT4KDik9gpnu0dZ0XebmEj27Qf_zBK-FV_n9wdnbjqTkqY_9ww9m0nY4hq1Vgp8D6mt1ymTcnBeAuvxNPIQevFNaKgV4Pt
WnIa9ligymPcegFo7vsbBx9teM93rdmDLRjk28YGVyryWP5BrP8pjOv4pHgDQdi7PhnuUu_nS2z5nAwaHwBdq0_w1ltbGtsF3hdY
k--VnkpGQwxupO2QQJwR9hsm6zTVo8qupGMLejbGMl2_JYO-7OqdU9fFuscuVYDYxrV92wo7UHIuzGG_DDZJjrXh6wfp6xRzVHT2
TsKRN2Ms49sGzlYazVFc5j64Ca_IfpA5tHoutfwMSBbsJgBY0-aLd3ib3DpSHZt2KzRxd74mcy6JbMe8PoHZ-Po2NoCiQULZBeZK
YzdEHh1nd1q9AjGUejXGI8yv02o3FPQ1ZIfMHxLpgIdx6BjZoFPqjcfZDXGkxf1YOzByQl7vsmMzRT4SGZI05vmBMBdugN_Q23ag
-myg-mZTbvr3ix4Yy1dhXZRMhvXu1ENSii2Jci2ip2UqxHIRAayo7ItBLojdy4b4E5Xv0gy7hiLbhrJB1QEigvm1nWj8keEq70oR
TM3fTKLKdWqBiROeMFAVE2vQtAcA7yi1fXUyQU7CkGrQZqErVuJZqsPU9Dt-9BL3hkEOYJ0siImIrcmnDJwA7Q1RNa4FMDWBtZW2
s5F1k792TRSjqxTGvRA2yhFW-ZbMksPyvTZGyS6vZQS64ceBmBBk-6q7ohncAJEyhkb2VnC3hvt0d5uhEJgLpEV-l03UCGSEPb5A
AWtvGH6cIwRegnOBmSXYqdZQpAqvSMqVZLQQ2_is1hVScgOkNBrQVTMwcPEXYhZib5Sdt_MB0eFC7Mbtba9jmIhbjtOg7KH0WggE
2WQrTStVXQnumwGVIze1BkESSEDUvl_XoXGAkxriBlbKEw8H8oPpMCSLu3Q0zWDg--
lqEoGJKe3eVWlPQih8EFU-7DQMFwCTwSR76V90BG3_wNm-j2Cg7pdpMbE0CrbachiEOrhRy-6NSmMuO1XY19USaGQDZC7rZi-ld9
EEZGOSrBRH9hA-X3JdyVevEzghh6fQRKAZ-w6n5gWOO8XnRU8C3p8E3Ut9p9WItEeOCvKsrjmONV093oJctOHJFMZX8HMzx2WT1i
E-Lr6fDGgRBn9vJhd85AifTLnq9jfChBcn5zgztur8QTaBmo8pgawJjhCxUFLbqQl4olAtkENtRLNYUexdC5qW7DRveumcVrIxzd
14tGIE0WnLM74Bka07mwlKoVAk39SB70wYFDR99jEapkmqk9gZiwos1iS73DNhDjZdAT6O0AZz6lf7fM9QaPOQG7HVN5AwQ3ZNfg
syUi1JpIMfmBtK2T4G0KHnUFUnm6Y-mha00QqPcasigGqlc7mANua5Jxmp9R5EBNSpgYNkLOQMSYqX2lrHIVVpHLnicrqEDOaWAz
HeUvuWx1x-HtnCiLQ9W9Gn4WSGD3roq6dO5GxEPpygWXhaIYFp-00SOpLTpKD2eSYssHGORDpQbV62akTll3ck-
gXGH5urCzgJaujh7kyRlX3WmbNNYGD7tViwAbg1S_6kYfOrIK4XwngGiAn5DbhvBFaviFGlonwWAJO5k_-Nh4TH9IU7vW715TXjU
ypvguTFCt9BFNGrwMMN1pyiGl9NH3vMOb7nGn1aCTHBWfPG8_zBpPFnzqU3mfUdajWZ6sGnXomXYpsn7nFi-e9ZIYaMVkywkMhHv
UUsgWnCk4bLvqYoXsnExMZaCXgzXQ0dwgf5sb5rqRQ7flogXCwVqR5l5U4w9HQiMKCwR4aZKah-S9Ezc81yAsDEpL5wRz-8YNCy8
Xg4ZagoohIxchFqOCcgqFp7Kk2NjxZ-hnaS5QnScF94PEqq2UK2eP864_vMqOQmTNUFDS9Kznpgsf52_z096_SeCpC_qoe-
iWb5r95bZ-evvLzSrg5o6lMasSI6DMgIV6SwZ3ucX4CBWV63ooL1IGh4WvJRgl0K68r2Ncy0NhOQrFOn7mXRg1-UbHYsRUTg2cKA
D7YxUK8-deXb19ZqWj5g953mBU6FJ6PqQpKcW3UrxPIDUMlO5Gwy3sGo3W3XBiciKRMOuOhqfZ3t8Jr2jphgeezkkm1uOUULPC8Y
bFBHu0uSxkuZWlsX2NzvMMrQmNSp-I7g9Ynn-R7Tz3xCeaT8vuownHxXoWXyeST27utdKRwBAWfJtOKBNE7KZh3voHjF6yBl44Tr
wiBaTUY_aZFqMrcuxDpU9-xN_Q1Uh6I9qXHeWVODZr2weR_ymT8gy6UCziiRso0JnfFEdpOhqGtqj3XIMJzkm2ZaEBZJ2zwInckK
kBLfHPM0qJomx7hHaZal7SK9hk7NyGUi0EjupQxLjf8bRbExEh-LIcLeAPIsTyBx9d2oMrfcaSBsyb2PM1sRTNBWqCanmmixD9yg
kgFrk1YELSXKxJe2NAxFaisoaEYZ0gMxOQPwOZMdqchGATk-g6VwFeMQ34q7nc7Tvc_FQzd86IlnFVsjq3rkv9YY-
cGhjH516KkxJ51TQ9NGc9KhrSFAUv-
mUh5BThApeCjKMl2Ifz7ocfTh566xdR8PmrNoa9YOngKzGpofAHbhJy8viw9ez0ah9PJpbsWi-
Vg60uEF3_YnOFRI68XtgVek5fBmmiFAZvVmP71QeM-jPeXN9XPn_8F3BKVIw==</pre>
</details>

**By submitting this issue I confirm that I am aware that this information can
potentially be used to determine what kind of calculation was performed at the
time of error.**

**Comment by mbercx** [comment]
Was able to reproduce this again by just clicking on different elements of the work chain tree back and forth. 😅

**Comment by danielhollas** [comment]
I think this is already fixed on master, a new version needs to be released @unkcpz

**Comment by unkcpz** [comment]
Yes, it is fixed by https://github.com/aiidalab/aiidalab-qe/commit/2e4c7faa50240071e80d855969a49e0643154412
