### ISSUE TITLE
Clean the remote workdir as default and provide checkbox for not clean up

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#370]
**Is your feature request related to a problem? Please describe.**
In the THEOS testing server, the storage space of active user increased dramatically. The issue comes from that the calculation folder is not cleaned up if run in localhost. 

**Describe the solution you'd like**
Clean up the remote workdir if the calculation finished successfully, provide the widget to tick the option to turn off clean up.

**Comment by AndresOrtegaGuerrero** [comment]
I think that this feature could be a checkbox in the AdvancedSetting tab

**Comment by mbercx** [comment]
Hmm, just off the top of my head: `clean_workdir` is an input of each work chain, and is not dynamically changed if the work chain fails. So I guess keep this to `False` (which will be default from the next release), and then use a similar implementation as in the `on_terminated` to clean if successful.
