### ISSUE TITLE
Show at least cell (even better coordinates) beside structural visualiser

### ISSUE THREAD

**Issue by giovannipizzi** [aiidalab/aiidalab-qe#374]
**Is your feature request related to a problem? Please describe.**
I search a structure with OPTIMADE (e.g. I want bulk Pt). I found two, and I have no obvious way to know which of the two I want (e.g. in my case from MC3D, I know one is cubic and one tetragonal, and I want the cubic one).

**Describe the solution you'd like**
I think it was there at some point: put back some way to see the cell vectors, and the atom coordinates. Even collapsible below it's OK as long as I can check those.

**Describe alternatives you've considered**
I couldn't find a way to do it (in addition, the "ID" from OPTIMADE I think is the PK, while on MC3D we use the mc3d-id, so I cannot even use that to decide which structure to pick.

**Comment by unkcpz** [comment]
Hi @giovannipizzi, the cell information is on the right of structure.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/8831685/227725129-374ef88a-ec95-44d3-981e-063eb220691a.png">

For the atom position, you need go to tab selection and select atom to check its coordinates. 
You can also convert it to a conventional cell (using structure editor) to make it looks more intuitive to recognize the symmetry.

**Comment by giovannipizzi** [comment]
Thanks, indeed closing - I think I was using an older version of the app
