### ISSUE TITLE
Make the output of QeAppWorkchain namespace of every sub-workchain

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#390]
The QeAppWorkchain now run the output of every sub-workchain to one level hierarchy output. Therefore the output ports are many and don't have clear categories for which one is output of which workchain. 
It will be more clear if every sub-workchain has its own namespace for output ports.

The current output ports are:

```
        spec.output('structure', valid_type=StructureData, required=False)
        spec.output('band_parameters', valid_type=orm.Dict, required=False)
        spec.output('band_structure', valid_type=BandsData, required=False)
        spec.output('nscf_parameters', valid_type=orm.Dict, required=False)
        spec.output('dos', valid_type=XyData, required=False)
        spec.output('projections', valid_type=Orbital, required=False)
        spec.output('projections_up', valid_type=Orbital, required=False)
        spec.output('projections_down', valid_type=Orbital, required=False)
```

better be sort of like:

```
        spec.output('final_structure', valid_type=StructureData, required=False)
        spec.output_namespace('relax', dynamic=True)
        spec.output_namespace('bands', dynamic=True)
        spec.output_namespace('pdos', dynamic=True)
```

**Comment by unkcpz** [comment]
After the plugin design, this one was also resolved. 
Nice job! @superstar54  Please confirm and close this issue.

**Comment by unkcpz** [comment]
Hi @superstar54, I just found this part of code still in the code base. I think this is the one must be done before the release, can you give it a estimate how much work and any blocker of it? 

See https://github.com/aiidalab/aiidalab-qe/blob/0eaf57114fc154690872f84522e0267620c6bc82/src/aiidalab_qe/workflows/__init__.py#L99-L106

**Comment by superstar54** [comment]
These outputs are used for the `electronic structure` result panel. The  `electronic structure` panel is still hardcoded because it needs the results from both `bands` and `pdos` plugins. When we find a good solution to support result from multiple plugin, we can remove both the code in the `electronic structure` result and the code in the workchain.

For the moment, we can remove the code in the workchain, but still hardcoded the `electronic structure` result panel.

**Comment by unkcpz** [comment]
I would suggest to do the change, bottom line we don’t want to make release with the new feature half way done. Could you also think about what Giovanni mentioned in your group meeting? If separate bands and dos in the result make the maintainance harder to follow the plug-in design, probably the better way is to having them as one?
