### ISSUE TITLE
Using update_settings to recover setting widgets from process

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#397]
In https://github.com/aiidalab/aiidalab-qe/pull/382 I add `_update_settings` method for `WorkChainSettings`, `KpointSettings` and `SmearingSettings`. In principle, the `builder_parameters` are converted from these three setting widgets and should be able to recover widgets settings from `builder_parameters`. I didn't do it in https://github.com/aiidalab/aiidalab-qe/pull/382 because an elegant way to serialize/deserialize between `builder_parameters` and widgets needs to implement and deserves a separated PR.

**Comment by unkcpz** [comment]
However, when I look at the refactored architecture in https://github.com/aiidalab/aiidalab-qe/issues/383, setting widgets directly from builder_parameters  is not ideal and pretty convoluted since it brings the entanglement between viewer and controller which is we want to avoid from first place. Instead, we need to introduce and use the data class for all the settings object and have bilateral converters between setting widgets and builder_parameters, and have this data class in the middle.

**Comment by superstar54** [comment]
This is fixed in plugin PR #485 .
