### ISSUE TITLE
Start a new workflow and reset some widgets but not all.

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#420]
1. Open a qe app in a new page
2. start a new calculation, and set "Structure as it is" (without relaxation), and override pseudopotential to SSSP precision.
3. using "New workflow" of workflow selector to start a new workflow
4. You'll find some widget is reset to default such as structure set to "Full geometry", but pseudopotential is still overrided.

I encounter this with `v23.04.3`, not sure if I fix some already during refactoring.

**Comment by superstar54** [comment]
fixed in #489
