### ISSUE TITLE
QEApp plugin implementation

### ISSUE THREAD

**Issue by superstar54** [aiidalab/aiidalab-qe#426]
Here is a summary of the idea of this plugin implementation. https://hackmd.io/Pze_b838SIKx150NAnFP1w

It is going to be a big change. To make it easy to review and ensure the changes are correct and robust. I am splitting it into several PRs:

- [x] PR 1, UI related (by June 30)
- [x] PR 2, workchain related
- [ ] PR 3, nice to have features
    - [ ] support structure plugin
    - [ ] Add panel for resources

**Comment by unkcpz** [comment]
See #469
