### ISSUE TITLE
Accelerate the loading speed of the App

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#455]
Opening the app takes a quite long time, check https://github.com/ispg-group/aiidalab-ispg to see how it benchmarks the time of loading and benchmark to find the bottleneck widgets.

**Comment by unkcpz** [comment]
@superstar54, I may don't have time to look at this this week. Since this is a critical blocker of the release of `23.10`, could you find time to investigate it a bit? 
As we discussed last week, you can try to update aiida-core which has @danielhollas's import improve implementation. I think the delay may also come from optimade widget, you can try to comment it out and test the load time.

Since we have moved out the app class as an independent one, I guess it is easy to benchmark by running `time python -c "from  aiidalab_qe.app import App; App(qe_auto_setup=True)"`

**Comment by danielhollas** [comment]
@superstar54 I'd recommend looking at this topic on Discourse to see how I benchmarked import time with `cProfile`
https://aiida.discourse.group/t/why-is-aiidalab-base-widget-import-so-slow/32

> As we discussed last week, you can try to update aiida-core which has @danielhollas's import improve implementation.

Note that you'll have to pull the latest `main` branch for this, my improvements have not been released in official version yet.

I would also recommend implementing #453, which can speed things up a lot, especially for users with a lot of finished workflows.

**Comment by superstar54** [comment]
> I would also recommend implementing https://github.com/aiidalab/aiidalab-qe/issues/453, which can speed things up a lot, especially for users with a lot of finished workflows.

@danielhollas Thanks. I looked at the code of `WorkChainSelector`. There is a big performance issue in the for loop. I will try to improve it. If it does not work, I will try to use your approach.
