### ISSUE TITLE
Following work for plugin design

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#469]
## mush have
- [x] add more tests, in the old `plugin_ui` PR, the test coverage is around 80%
- [x] rewrite `set_panel_value` for `advanced_settings`, so we can load data from the process. This needs some improvement from sub-widgets.
- [x] add a clear doc for the plugin.

## Nice to have improvement
- [x] add entry point for step, allowing the user to add new structure importer and editor.
- [x] add entry_point for step 3, allowing the user to add code widget for their plugin.
- [x] update the result panel, so that it can combine results from different plugins, e.g. bands and pdos.

**Comment by superstar54** [comment]
I am happy to close this issue because all items are done.
