### ISSUE TITLE
Define dataclass for builder parameters with report displayed name for each field

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#484]
The `builder_parameters` is stored as the extra attributes of workchain and used to print the report in the summary widget. Howover, the summary widget has filed name defined in `_generate_report_dict`. For example, "relax_method" is as displayed a field name for key "relax_type" in builder parameters. 
It is error-prone that these two related information are given in two places. Ideally, when new field is added to `builder_parameters`, the displayed name should given along with it.

**Comment by superstar54** [comment]
> It is error-prone that these two related information are given in two places. 

Fixed in #481
