### ISSUE TITLE
HTML kpoints mesh 

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [aiidalab/aiidalab-qe#488]
We should re-consider not using the `create_kpoints_from_distance` an instead use one that is not a calc_function
because everytime we change the kpoints_distance it creates an aiida_node 

![Screenshot 2023-09-25 at 15 20 24](https://github.com/aiidalab/aiidalab-qe/assets/34098967/07ec387d-b3ae-4e4e-ba25-2c9d03ed7f30)

**Comment by unkcpz** [comment]
I personally don't think this is a problem, and I think we should use calcfunction/workfunction as more as possible to keep full provenance. Is this a calcfunction called from qeapp or it is from `aiida-quantumespresso`?

**Comment by AndresOrtegaGuerrero** [comment]
This from` aiida-quantumespresso`. The full provenance is just kept once you launch the QeAppWorkChain, since you save the mesh you used, and this is just for giving a GUI to the user , and the mesh is kept in the output of the PwBaseWorkChain

**Comment by unkcpz** [comment]
Since it is from qe plugin, I would worry about it for the qeapp. Maybe create an issue on qe plugin and close this one?

**Comment by AndresOrtegaGuerrero** [comment]
I will close it here, but i dont think is a good idea to open a ticket for the qe plugin, since that calcfunction is used within the workchain, so it makes sense to keep the provenance, while in our case we are just using it for GUI

**Comment by superstar54** [comment]
I reopen it because this is not a issue for `aiida-quantumespresso`. It's a issue for QeApp.
