### ISSUE TITLE
List and discuss the name for the plugin design

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#496]
Thanks to the great work contributed by @superstar54, the plugin design allows new property developers can focus on the functionality and widgets needed for the property itself without knowledge of how other part of QeApp works. 
It decouples the settings of parameters of different calculations by introducing the "Panel" as the base widget class which has some common functionality to interact with other parts of the code.
There are some terminology and methods used but not intuitively straightforward to know what is for, such as "identifier", "get_panel_value" etc.
@superstar54, can you make a list of these names and we can have a discussion with @giovannipizzi? Once we make the stable release at the end of this month, it become a new API for developers and will be hard to change after.

**Comment by unkcpz** [comment]
During @superstar54's group meeting, we agreed that we release this `v23.10.0` with current names for APIs, and when there are more developers trying plugin design, we discuss and fix the API in the next version.

**Comment by unkcpz** [comment]
Pining @AndresOrtegaGuerrero @PNOGillespie @mikibonacci who start implement the plugins, do you find some class names are not clear or bring ambiguity? If those are all fine, we can close this PR.

**Comment by mikibonacci** [comment]
Hi @unkcpz, I do not have in mind examples, so for me everything is fine

**Comment by unkcpz** [comment]
Thanks @mikibonacci @PNOGillespie for the feedback. 

@superstar54 Can you keep track on this issue and make sure the advice from @PNOGillespie above is happened on the `v24.04.0`?
