### ISSUE TITLE
Some layout issues that deteriorate UX

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#528]
The tabs are out of box in some panels:

<img width="589" alt="image" src="https://github.com/aiidalab/aiidalab-qe/assets/8831685/2b1f747f-abaa-4ed2-9336-c6c10bf1f2ee">

- The "Band structure settings" do not show properly in the tab. 
- "Pdos Settings" -> "PDOS settings"

In result panel:

<img width="734" alt="image" src="https://github.com/aiidalab/aiidalab-qe/assets/8831685/60ddb836-562e-453a-aa1b-d811845232a4">

- The "Electronic structure (n/a)" is overbox.
- "** not available." -> "The calculation of ** is still running, please wait and the result will show after the calculation is finished."

@superstar54 could you have a look at this?

**Comment by superstar54** [comment]
The result panel is fixed in #522 , which only shows the result panel when it is available.
