### ISSUE TITLE
List of qeapp plugins to be easily installed

### ISSUE THREAD

**Issue by mikibonacci** [aiidalab/aiidalab-qe#571]
As the new plugin implementation is there, would be nice to have, in the future, the possibility to access and install the developed qeapp plugins from the aiidalab homepage. For example, a dropdown list aside the qe logo here:

<img width="988" alt="Screenshot 2023-11-29 at 09 09 07" src="https://github.com/aiidalab/aiidalab-qe/assets/46074008/ea4362ce-e9cb-4b50-a9e9-fc37bcc5b430">

So far, to install plugins (e.g. [aiidalab-qe-muon](https://github.com/mikibonacci/aiidalab-qe-muon)) you need to clone them and pip install manually.

**Comment by superstar54** [comment]
Indeed, it would be nice to show the existing plugins in the GUI, and let the user manage (install and uninstall) the plugins.

I am working a `qeapp-rplugin-egistery` repo, and the developers can register their plugins there. Will be online soon. After that, we can update the GUI by the data in the repo.

**Comment by unkcpz** [comment]
I guess you mean `qeapp-plugin-registry`? :) @superstar54
