### ISSUE TITLE
✨ NEW: Add limit to number of atoms in structure

### ISSUE THREAD

**Issue by mbercx** [aiidalab/aiidalab-qe#60]
Since the amount of resources that are typically available on demo/testing deployments is limited, calculating structures with large unit cells will take far too long (if they can even complete). We should put an upper limit on the amount of atoms in the (primitive) unit cell that the app will allow for submission. An error message should appear, clearly stating that "for this demo deployment only structures with a size smaller than X" can be calculated.

If you can figure out the resources at your disposal, you could adjust this size to what's available, and automatically set the max you can spare on this machine in the (hidden) resources tab of Step 2. Hopefully at some point we'll be able to get a halfway decent TTS (time to solution) and memory usage predictor, but until then we have to just play it safe and keep the structures smaller.

We could also have three ranges (e.g. on one core - some might take long though.):

* X <= 6: No problemo!
* 6 <= X <= 10: Raise warning
* \> 10: Raise error

**Comment by csadorf** [comment]
Resolved with https://github.com/aiidalab/aiidalab-qe/commit/c737379e2ea70ec2e14d51b09248927c290effd5 .
