### ISSUE TITLE
🐛 FIX: Reset of work chain settings when choosing a new structure

### ISSUE THREAD

**Issue by mbercx** [aiidalab/aiidalab-qe#61]
After setting your work chain configuration in Step 2 and going back to select a different structure, the work chain settings are suddenly reset:

![fix_61](https://user-images.githubusercontent.com/25607960/120968519-42bb5980-c769-11eb-912f-7d297c4d97dd.gif)

Ideally this shouldn't happen, but at the very least this pathway shouldn't be possible.

**Comment by yakutovicha** [comment]
That bug is not present anymore - the settings remain unchanged.
