### ISSUE TITLE
Plotly bands plot widget

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#626]
The new bands plot widget is merged https://github.com/aiidalab/aiidalab-qe/pull/581, thanks for the great work! @AndresOrtegaGuerrero 

There are more to improve on the widget:

- [x] The fat bands plot support https://github.com/aiidalab/aiidalab-qe/pull/624
- [x] The performance of new implementation is not very good at performance.

**Comment by AndresOrtegaGuerrero** [comment]
@unkcpz Could you have a look on #512 , that one also addresses changes in the widget to satisfy tot_magnetization calculations
