### ISSUE TITLE
Strange code name from daint-gpu

### ISSUE THREAD

**Issue by bio15** [aiidalab/aiidalab-qe#628]
I used daint, gpu and QE.
I got `pw-7.2}}@daint-gpu`, it has this strange `}}` inside.

**Comment by unkcpz** [comment]
@superstar54, maybe you can make some record when having in person test with @bio15?

**Comment by superstar54** [comment]
@unkcpz here is the record.
https://github.com/aiidalab/aiidalab-qe/assets/11457659/a9292afb-fcc1-49ac-9728-0cbe8c204f2a

**Comment by unkcpz** [comment]
Should be fixed by https://github.com/aiidateam/aiida-resource-registry/pull/15.
