### ISSUE TITLE
🐛 FIX: Structure not showing in the "Final Geometry" tab of the outputs.

### ISSUE THREAD

**Issue by mbercx** [aiidalab/aiidalab-qe#69]
In Step three, the `StructureDataViewer` in the "Final Geometry" tab is not showing the structure properly. This is most likely related to this issue:

https://github.com/nglviewer/nglview/issues/871

There is a suggested fix there, but I didn't manage to get this to work yet. This may be due to the convoluted logic I implemented to have these `Tab`s only show up once the results are completed.

**Comment by yakutovicha** [comment]
I looked into the issue, and it seems that the behaviour remains exactly as it was: the structure is displayed in the first tab, but not displayed in all the others:

<img width="1030" alt="Screenshot 2021-06-29 at 11 05 41" src="https://user-images.githubusercontent.com/13118485/123770351-874e9680-d8ca-11eb-88f9-d3fd9562ac45.png">

**Comment by csadorf** [comment]
> I looked into the issue, and it seems that the behaviour remains exactly as it was: the structure is displayed in the first tab, but not displayed in all the others:

Does that mean there is no fix?

**Comment by mbercx** [comment]
So it's exactly the same as the issue you encountered, or?

**Comment by yakutovicha** [comment]
I think there is a fix, but it might be an ugly one. Trying to figure it out.

**Comment by yakutovicha** [comment]
Yes, it is exactly the same issue that I encountered before.

**Comment by mbercx** [comment]
Ugly fixes are better than no fixes. 😁

**Comment by csadorf** [comment]
Resolved with merge of #92 .
