### ISSUE TITLE
✨ NEW: Widget for setting magnetic configuration

### ISSUE THREAD

**Issue by mbercx** [aiidalab/aiidalab-qe#70]
Not something I would add to the "Public release" project, but more of a long-term idea:

The user can now specify whether or not they think a material is magnetic or not. This will then use the rudimentary approach we have set up in `aiida-quantumespresso` that just sets up a ferromagnetic high-spin configuration.

This is a fine first step, but more advanced users will want to be able to choose the magnetic configuration. Having a widget for doing this in an intuitive manner will be challenging, but a great addition to the QEapp.

**Comment by AndresOrtegaGuerrero** [comment]
The current QeApp now has starting magnetization , tot_magnetization , and also they can defined labels for the atoms to define a magnetic configuration
