### ISSUE TITLE
Controlling the walltime of calculations

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [aiidalab/aiidalab-qe#709]
For some calculations, a user my request a longer time than 12 hours, 
There should be a widget that the user can modify this in case is needed.

**Comment by mikibonacci** [comment]
Hi @AndresOrtegaGuerrero, I did something [here](https://github.com/mikibonacci/aiidalab-qe-muon/blob/feature/code_res/aiidalab_qe_muon/app/codes.py) 

Maybe I can add something similar ( I have to see if it work with the new release) in the app.

**Comment by AndresOrtegaGuerrero** [comment]
@mikibonacci you can put it in the computational resources widget ?

**Comment by mikibonacci** [comment]
Yep, I will do it
