### ISSUE TITLE
Job List not displaying, Checkbox instance expected a unicode string, not the float nan

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [aiidalab/aiidalab-qe#726]
---------------------------------------------------------------------------
TraitError                                Traceback (most recent call last)
/tmp/ipykernel_37775/1471599892.py in <cell line: 3>()
      1 from aiidalab_qe.app.utils.search_jobs import QueryInterface
      2 
----> 3 qi = QueryInterface()
      4 qi.filters_layout

~/apps/quantum-espresso/src/aiidalab_qe/app/utils/search_jobs.py in __init__(self)
     10         self.df = self.load_data()
     11         self.table = ipw.HTML()
---> 12         self.setup_widgets()
     13 
     14     def load_data(self):

~/apps/quantum-espresso/src/aiidalab_qe/app/utils/search_jobs.py in setup_widgets(self)
     83         unique_properties = set(self.df["Properties"].explode())
     84         unique_properties.discard(None)
---> 85         property_checkboxes = [
     86             ipw.Checkbox(
     87                 value=False,

~/apps/quantum-espresso/src/aiidalab_qe/app/utils/search_jobs.py in <listcomp>(.0)
     84         unique_properties.discard(None)
     85         property_checkboxes = [
---> 86             ipw.Checkbox(
     87                 value=False,
     88                 description=prop,

/opt/conda/lib/python3.9/site-packages/ipywidgets/widgets/widget_bool.py in __init__(self, value, **kwargs)
     22         if value is not None:
     23             kwargs['value'] = value
---> 24         super(_Bool, self).__init__(**kwargs)
     25 
     26     _model_name = Unicode('BoolModel').tag(sync=True)

/opt/conda/lib/python3.9/site-packages/ipywidgets/widgets/widget.py in __init__(self, **kwargs)
    475         """Public constructor"""
    476         self._model_id = kwargs.pop('model_id', None)
--> 477         super(Widget, self).__init__(**kwargs)
    478 
    479         Widget._call_widget_constructed(self)

~/.local/lib/python3.9/site-packages/traitlets/traitlets.py in __init__(self, *args, **kwargs)
   1345             for key, value in kwargs.items():
   1346                 if self.has_trait(key):
-> 1347                     setattr(self, key, value)
   1348                     changes[key] = Bunch(
   1349                         name=key,

~/.local/lib/python3.9/site-packages/traitlets/traitlets.py in __set__(self, obj, value)
    730             raise TraitError('The "%s" trait is read-only.' % self.name)
    731         else:
--> 732             self.set(obj, value)
    733 
    734     def _validate(self, obj, value):

~/.local/lib/python3.9/site-packages/traitlets/traitlets.py in set(self, obj, value)
    704 
    705     def set(self, obj, value):
--> 706         new_value = self._validate(obj, value)
    707         try:
    708             old_value = obj._trait_values[self.name]

~/.local/lib/python3.9/site-packages/traitlets/traitlets.py in _validate(self, obj, value)
    736             return value
    737         if hasattr(self, "validate"):
--> 738             value = self.validate(obj, value)
    739         if obj._cross_validation_lock is False:
    740             value = self._cross_validate(obj, value)

~/.local/lib/python3.9/site-packages/traitlets/traitlets.py in validate(self, obj, value)
   2534                 msg = "Could not decode {!r} for unicode trait '{}' of {} instance."
   2535                 raise TraitError(msg.format(value, self.name, class_of(obj))) from e
-> 2536         self.error(obj, value)
   2537 
   2538     def from_string(self, s):

~/.local/lib/python3.9/site-packages/traitlets/traitlets.py in error(self, obj, value, error, info)
    842                         describe("the", value),
    843                     )
--> 844                 raise TraitError(e)
    845 
    846     def get_metadata(self, key, default=None):

TraitError: The 'description' trait of a Checkbox instance expected a unicode string, not the float nan.

**Comment by superstar54** [comment]
@AndresOrtegaGuerrero, could you give some hints on how to reproduce this error?

**Comment by AndresOrtegaGuerrero** [comment]
@superstar54 I am actually trying to find the source to reproduce it

**Comment by AndresOrtegaGuerrero** [comment]
@superstar54 i think the sources is do to using an external plugin ? that the prop is as nan ?

**Comment by AndresOrtegaGuerrero** [comment]
I think this problem it occurs when you install an external plugin, run a calculation , and then you uninstall the plugin

**Comment by superstar54** [comment]
Another situation is that a user does not select any property and also does not run relax :joy:

**Comment by AndresOrtegaGuerrero** [comment]
but the nan should be now be avoided in the job list, right

**Comment by superstar54** [comment]
Yes, I think so.
