### ISSUE TITLE
👌 IMPROVE: Find way to give clean error message when things break

### ISSUE THREAD

**Issue by mbercx** [aiidalab/aiidalab-qe#74]
Currently, when things break because an error is raised, the whole Trace is printed out, and things get funky. It would be better if we could somehow catch this and give a clean error messages that creates a report (strack trace + state + inputs?) that is stored on the cluster.

**Comment by csadorf** [comment]
The feature is implemented here: https://github.com/aiidalab/aiidalab-widgets-base/pull/209

**Comment by csadorf** [comment]
Resolved with merge of #91 .
