### ISSUE TITLE
Walltime doesnt apply to plugin (vibroscopy)

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [aiidalab/aiidalab-qe#754]
When using the definition of the walltime for the plugin (vibroscopy) it doesnt work , i am not sure if it is the case for the other plugins.

**Comment by AndresOrtegaGuerrero** [comment]
@mikibonacci I fixed for the vibroscopy, I dont know about the other external plugins

**Comment by superstar54** [comment]
If a plugin developer uses `set_component_resources` function, then the `max_wallclock_seconds` will work.

**Comment by AndresOrtegaGuerrero** [comment]
We need to modify the workchain in the plugin to use `set_component_resources` , we need to adapt it to ignore the parallelization (it create will crash in the dielectric part) . @mikibonacci and I will work on defining specific resources for the phonons and for dielectric workflows , adapt it to `set_component_resources` from aiidalab_qe and do a new release.
