### ISSUE TITLE
Bug for Core-Hole SCF Calculations Combined with DFT-D3 Correction

### ISSUE THREAD

**Issue by PNOGillespie** [aiidalab/aiidalab-qe#765]
**Describe the bug**
(From AiiDA-QE) When running core-hole SCF calculations in the `XpsWorkChain` and `XspectraCrystalWorkChain` with default settings in combination with the Grimme D3 vdW correction, the SCF calculation returns `NaN` for the total energy. This is because the DFT-D3 module of QE sets D3 parameters based on the `ATOMIC SPECIES` name, but if the name is not a valid element symbol then the program continues to the SCF procedure rather than crashing due to the unidentified element symbol.

This will happen using the default settings for both `WorkChain`s because the default `abs_atom_marker` is set to `X`:
![SCF_Input_File-Default_Absorber](https://github.com/aiidalab/aiidalab-qe/assets/55498719/e41d86a2-b3e3-4c2f-b426-22c0324bdca4)
![D3_Terms_Table-Missing_Absorber](https://github.com/aiidalab/aiidalab-qe/assets/55498719/fa57df22-de05-4e88-a5b5-94f67d936a63)
![D3_Terms_Total-Missing_Absorber](https://github.com/aiidalab/aiidalab-qe/assets/55498719/48a3de01-45c5-4c07-9b5c-c197a9a8261a)
![D3_Terms_Total-Absorber](https://github.com/aiidalab/aiidalab-qe/assets/55498719/8cbf2669-6dbc-4e83-936e-5e877f3cfa17)
![SCF-Final_Energy_NaN](https://github.com/aiidalab/aiidalab-qe/assets/55498719/4f9330fb-6353-4227-b25a-976f93c97a2d)

**Proposed Solution**
Changing the absorbing atom to `<element_symbol><number>` easily fixes the issue, as numbers are automatically trimmed when the DFT-D3 module reads the species name:
![SCF_Input_File-C1_Absorber](https://github.com/aiidalab/aiidalab-qe/assets/55498719/527815b9-d2f9-469f-adab-80ee8e4537de)
![D3_Terms_Table-C1_Absorber](https://github.com/aiidalab/aiidalab-qe/assets/55498719/2eb2ec4a-c70d-40ed-ac14-aa8aae2fb8b5)

For `AiiDA-QE`, this is possible through overrides, however there is currently no way to set the `abs_atom_marker` in `AiiDALab-QE` and thus the `WorkChain`s will fail unless the absorbing atom marker is changed.

**Comment by superstar54** [comment]
> For AiiDA-QE, this is possible through overrides

Do you mean override manually? )r there is an automatical way to set <element_symbol><number>?
