### ISSUE TITLE
Discussion: Should we build qeapp image for arm64?

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-qe#775]
The current docker CI machinery is very complex. If we could ditch the arm64 build, it would become much much simpler and easier to maintain. Given that the arm64 build is likely mainly for developers, I would propose to ditch it and only build for x86. Developers can always use the full-stack image. In fact I think it is beneficial if some devs work from the latest full-stack image so that it receives more dogfooding that way.

NOTE: The arm64 is currently failing, if you want to keep it, we need to switch it to buildjet runners.

WDYT @unkcpz @superstar54

**Comment by unkcpz** [comment]
In the exist k8s server those are all amd64. Not sure if @mikibonacci and @AndresOrtegaGuerrero who has apple M1/M2 are using qe image or you are running on aiidalab-launch with `full-stack` and then install QeApp from appstore?

**Comment by unkcpz** [comment]
I'd vote for removing it. If really needed in the future, it is still easy to bring it back.

**Comment by danielhollas** [comment]
Yes, I think we need to unblock ourselves. I'll remove it for now, and we can revisit in the future. Also I think we should still try to speed up the overall installation process when using the full-stack image. One thing will be swithing to Python 3.11 and pre-installing AWB.

**Comment by danielhollas** [comment]
Here's the biggest argument for removal

![image](https://github.com/user-attachments/assets/9c5da098-a2ec-4b2a-a064-007e3c878a92)

**Comment by unkcpz** [comment]
I asked @mikibonacci in person and he is okay with it. He uses `full-stack` image.
