### ISSUE TITLE
👌 IMPROVE: Set max resources based on computer

### ISSUE THREAD

**Issue by mbercx** [aiidalab/aiidalab-qe#79]
Currently the user can specify whatever resources he/she likes in the `ResourceSelectionWidget`. This can lead to calculations failing, but also to significant slowdowns when the code is run on the `localhost`. I see three things that we should improve here:

- [x] Allow the user to specify resources separately for each code.
- [x] Determine the max number of CPU's available. For the `localhost`, this can be achieved with `os.cpu_count()`. For the remote computers, this is usually specified as `mpiprocs_per_machine`.
- [x] Limit the amount of resources that can be specified:
  * Nodes: 1 for the `localhost`. For the remote computer, we should perhaps let this be configurable and stored as an extra?
  * CPUs: For the remotes, this should be `mpiprocs_per_machine` by default and also enforced as a maximum. The localhost should probably leave at least 1 CPU, so maybe `max(1, os.cpu_count() - 1)` should be the maximum?

Since we'll be touching this part of the code, I think it makes sense that we also:

- [x] Disable the `dos.x` and `projwfc.x` codes when the PDOS is not being calculated.

**Comment by csadorf** [comment]
Partially addressed by #96 .
