### ISSUE TITLE
~0.5 s overhead with tar

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#791]
I looked into container runtime a bit and learned that it actually doing `tar` for every layer. It means the tar we did for home did not help with saving size.
Meanwhile untar the `home.tar` cost ~0.5s in my nice workstation. 
I think we can simply cp home to `/opt/store/home` (try to add in #790 as the folder in the `/opt` with correct permission) and using `mv` which takes basically no time since I assume it just move the pointer to file and update metadata of location.

**Comment by danielhollas** [comment]
> using mv which takes basically no time since I assume it just move the pointer to file and update metadata of location.

I don't think that's true in general. The home folder will be on Docker volume or bind mounted and so on different filesystem, so I think you'll end up copying the files.

> I looked into container runtime a bit and learned that it actually doing tar for every layer. 

What do you mean by this exactly? Can you provide a simple example? I think it makes sense that it has to touch all the layers if you are taring the whole home folder which is composed of different layers?

> It means the tar we did for home did not help with saving size.

But we did not expect the archive to save size, did we? Unless we are adding compression, the tar file is just a useful way of packing all files into one. I would be surprised if copying /moving individual files would be much faster.

**Comment by unkcpz** [comment]
>  The home folder will be on Docker volume or bind mounted and so on different filesystem

This is true which I didn't  realized..

**Comment by unkcpz** [comment]
> > I looked into container runtime a bit and learned that it actually doing tar for every layer.
>
>What do you mean by this exactly? Can you provide a simple example? 

If you do `docker save <image> -o <image>.tar` and then untar it, you'll find each layer is a folder and each folder has a tar inside.
