### ISSUE TITLE
Check that all info is properly reset when clicking “new workflow…”

### ISSUE THREAD

**Issue by superstar54** [aiidalab/aiidalab-qe#814]
Check that all info is properly reset when clicking “new workflow…” (or simply replace with a full refresh of the page? SEE ALSO OTHER POINT BELOW). E.g. description, codes, pools, … (to be checked in detail; check also advanced settings, also for plugins), bonds of Si remain.

**Comment by giovannipizzi** [comment]
This does not apply anymore now, since the 'new workflow' button simply opens a new tab?

**Comment by edan-bainglass** [comment]
Correcto! Closing.
