### ISSUE TITLE
The sentence “Currently only 3D structures supported” is not true anymore

### ISSUE THREAD

**Issue by superstar54** [aiidalab/aiidalab-qe#817]
The sentence “Currently only 3D structures supported” (Text written at beginning of Step 1) is not true anymore, right? Please remove this sentence.
- Instead, in the structure editor, under “Edit StructureData”, add also “no periodicity” as an option. And test for a molecule if this works. (E.g. all mesh of k-points become 1x1x1 = Gamma only). E.g. try PDOS of a molecule, we have ETFA molecule (add also a simple molecule like O2 or CO2 to the examples!).
- In any case, ensure that the issue discussing what needs to be done for low-dimensional systems (e.g. what to relax, whether to add a Martyna-Tuckermann or similar, how many k-points, …) is in the milestone for the release in 6 months (~march 2025).ma

**Comment by cpignedoli** [comment]
also connected to https://github.com/aiidalab/aiidalab-qe/issues/734
