### ISSUE TITLE
Combine the 3 tabs: bands, El. Structure and PDOS into a single top-level band, called “Electronic structure”

### ISSUE THREAD

**Issue by superstar54** [aiidalab/aiidalab-qe#818]
- In the plugin input checkboxes, call the properties “Electronic structure (bands)” and “Electronic structure (PDOS)” to make it clear it’s going to be in the “Electronic structure” output tab in the end.
- If it’s easy, only show one advanced input tab for both called “Electronic structure”: there are not too many advanced options, so you can just put both the PDOS and bands in the same tab. Otherwise OK to keep as it is now, but give the very same name to the tabs as the checkboxes: “Electronic structure (bands)” and “Electronic structure (PDOS)”.
In the output, only show a single “Electronic structure” results tab.
- As a first simple step, just move three tabs inside this tab, calling them: “Bands only”, “PDOS only”, “Combined bands+PDOS”
In the future, open an issue (to be then rediscussed for the next release) whether we have no internal tabs, we have only the combined plot, and we simply have some checkbox or similar (e.g. a dropdown?) to decide what to show.

**Comment by edan-bainglass** [comment]
Moving comment from duplicate project item:

In Step 2.1 rename to:
Electronic projected density of states (PDOS)

In the Results tabs, only one, the name depends on what is computed:
Electronic PDOS
Electronic bands
Electronic bands + PDOS
