### ISSUE TITLE
Improve the band structure advanced tab

### ISSUE THREAD

**Issue by superstar54** [aiidalab/aiidalab-qe#819]
Band structure advanced tab: in 3D there is nothing to do. In 2D, we should write a simple function that automatically determines which lattice to use. Therefore, the tab should be completely removed.
Should for now be too complex to make the automatic selection, at least have a function that replaces the message and dropdown in the advanced “bands” tab with a simple message “No custom settings for the band structure of a 3D material are needed.” shown.

**Comment by AndresOrtegaGuerrero** [comment]
This is addressed in #787
