### ISSUE TITLE
Add download buttons

### ISSUE THREAD

**Issue by superstar54** [aiidalab/aiidalab-qe#823]
In workflow summary, add 2 download buttons:
.aiida file
Verdi process dump (zipped)

**Comment by AndresOrtegaGuerrero** [comment]
Should instead the download button be ,

` verdi archive create qe_app_calc.aiida --nodes {qe_node}`
 
but also include the Import QeAppNode to allow the users share results ?

`verdi archive import {upload node}.aiida`

**Comment by mikibonacci** [comment]
We just need to make sure that they are importing `QeAppWorkChain`, otherwise they will not see it in the app... well, they can always just want to import structures and codes, or entire profiles
