### ISSUE TITLE
Improve the bands plot

### ISSUE THREAD

**Issue by superstar54** [aiidalab/aiidalab-qe#875]
- can we remove the splines on the bands, that make bands weird when there are discontinuities? (See attachment)
- can we increase the max value of the slider of flat bands, when one is looking to the whole large band structure (here LiO)?

![image](https://github.com/user-attachments/assets/92c8851b-a9bb-45c4-8bce-648c0633f0fe)

![image](https://github.com/user-attachments/assets/1da05b3b-4245-42a3-8110-a6afebbdc8d2)

**Comment by AndresOrtegaGuerrero** [comment]
Could you add the attachment?
