### ISSUE TITLE
Two projwfc.x code

### ISSUE THREAD

**Issue by superstar54** [aiidalab/aiidalab-qe#879]
- If I select “Fat bands”, I need to select twice the projwfc code - can the same be reused? Or at least, change the name so that user know which plugin the projwfc.x code belongs to?
- In addition, if one does only bands without fat bands, it shouldn’t require projwfc.x, right?

**Comment by AndresOrtegaGuerrero** [comment]
Yeah , i think we had this discussion , you mentioned there is needed a PR before allowing this ? or not really ?

**Comment by superstar54** [comment]
Yes. two options come to my mind:
### option1

like the step 2, we add a tab for each plugin to select the code
### option2
since the code setup is usually short, so we can setup code in one tab, but add a section for each plugin

**Comment by superstar54** [comment]
I drew a diagram for the design discussion.

**Comment by superstar54** [comment]
Yes, it fixed in #939.


> If so, can we move this issue to the QE app repo and reference it in the PR?

I don't understand "move the QE app repo".
