### ISSUE TITLE
Explain how the (useful!) _estimate_min_cpus was defined?

### ISSUE THREAD

**Issue by superstar54** [aiidalab/aiidalab-qe#887]
The warning message related to calculator too big suggests “>= 100 cpus) this suggestion originates from max(100,estimate_min_cpus). Can you explain how the (useful!) _estimate_min_cpus was defined? Can we have a notebook or python script with the data, to be able to further discuss and refine over time?
![Image](https://github.com/user-attachments/assets/7db16bff-375b-4cbf-85bb-9c2f07233d3d)

**Comment by mikibonacci** [comment]
I added more details in the `_estimate_min_cpus` method, but basically I used parameters on number of atoms, volume, cpus, scf_cycles and time for a moderate relax run of SiO2, and then I found the power laws of the following formula 

```python
num_cpus = num_cpus0 * (n/n0)^3 * (v/v0)^(3/2) * (scf_cycles * t0)/tmax
```

using other simulations on SiO2, Silicon and Gold. This is very rough, and actually I plan to find a new more accurate model for this.
