### ISSUE TITLE
Job remain in the queue if 2 cpus are requested.

### ISSUE THREAD

**Issue by superstar54** [aiidalab/aiidalab-qe#888]
If we request 2 cpus the job remains in the queue. Add message (even block this for localhost; check in general if it’s possible to know the # of CPUs and warn if > than the default, for any computer (if default is specified)?

**Comment by unkcpz** [comment]
I believe this should be done from front-end widget. The number of CPUs info is explicitly set for the computer by the logic at 
https://github.com/aiidalab/aiidalab-qe/blob/b34e9971b0ce71003d9e0ef8d3829fe8d74a1bef/before-notebook.d/43_start-hq.sh#L48C1-L59C2

The num_cpu set up widget should read from this info and when the number in exceed a warning should be throw out.

**Comment by mikibonacci** [comment]
Hi @superstar54 and @unkcpz , I fixed the estimation of localhost available cpus [here](https://github.com/aiidalab/aiidalab-qe/pull/971), and I added this also in setting the maximum num_cpus we can set for a code (see [here](https://github.com/aiidalab/aiidalab-qe/pull/971/files#r1885706719)). I think this should be sufficient fix.
