### ISSUE TITLE
Confirm button does not work when go back to previous step

### ISSUE THREAD

**Issue by superstar54** [aiidalab/aiidalab-qe#894]
If I went to Step 3, then go back to step 2 to modify something, the ‘confirm’ button does not open again step 3 (I think it should)

**Comment by edan-bainglass** [comment]
Is this still an issue? Note that the current design choice is such that once a job is submitted, there is nothing short of direct HTML hacking (right click -> inspect) that can turn the submit button back on. The idea is that if you want to run a new calculation, click the New Calculation button.
