### ISSUE TITLE
Increase flat bands max

### ISSUE THREAD

**Issue by superstar54** [aiidalab/aiidalab-qe#899]
If one wants to show all bands (including semicore) the max 0.76 eV is too small. Would it be possible to have the max up to 5eV for instance? Or can this be a “relative line thickness”? (Check e.g. gold fast PDOS and show all)

**Comment by superstar54** [comment]
Hi @AndresOrtegaGuerrero , I think you already increased the `max`. 

> Or can this be a “relative line thickness”? (Check e.g. gold fast PDOS and show all)

Do you have any idea on this?

**Comment by AndresOrtegaGuerrero** [comment]
No , i already increase the thickness @timrov do you have some suggestions ,

**Comment by edan-bainglass** [comment]
@superstar54 @AndresOrtegaGuerrero what's the status of this one?
