### ISSUE TITLE
In step 3 warnings, number of CPUs should be estimated from Computer setup

### ISSUE THREAD

**Issue by mikibonacci** [aiidalab/aiidalab-qe#937]
We should rely on the default number of CPUs, as the python os.get_cpus (or similar) will not correctly work on deployments where host and single instance have different number of dedicated cores (which is almost always the case, the single instance will always have only a fraction of the host resources)

**Comment by edan-bainglass** [comment]
Hi @mikibonacci. Is this yet to be implemented? It is something additional to your recently implemented warning system?

**Comment by mikibonacci** [comment]
Hi @edan-bainglass, yes, it needs to be implemented. Is a fixing to the warning system. The issue is that now we estimate the available cores using python, but this detects the total cores of the host system, not the one assigned to the container (this is an issue mainly in kubernetes clusters, e.g. demo server). We need to get the number of available cpus from the code setup parameters, defined when the qe default codes are installed (if I remember correctly, @unkcpz told me that this is done when the container is generated, right?). 

I still need to check this, should happen this week

**Comment by unkcpz** [comment]
> if I remember correctly, @unkcpz told me that this is done when the container is generated, right?).

Yes, it is set after container start bind to the computer node setup. By `verdi computer show <localhost-hq>` you can see the number of CPUs can be used (and by API as well).
