### ISSUE TITLE
Bug report: Application crashed with ValidationError 

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [aiidalab/aiidalab-qe#942]
## Automated report

_This issue was created with the app's automated bug reporting feature.
Attached to this issue is the full traceback as well as an environment
fingerprint that contains information about the operating system as well as all
installed libraries._

## Additional comments (optional):

_Example: I submitted a band structure calculation for Silica._

## Attachments

<details>
<summary>Traceback</summary>

```python-traceback
~/aiida-quantumespresso/src/aiida_quantumespresso/data/hubbard_structure.py in append_hubbard_parameter(self, atom_index, atom_manifold, neighbour_index, neighbour_manifold, value, translation, hubbard_type)
    131 
    132         hp_tuple = (atom_index, atom_manifold, neighbour_index, neighbour_manifold, value, translation, hubbard_type)
--> 133         parameters = HubbardParameters.from_tuple(hp_tuple)
    134         hubbard = self.hubbard
    135 

~/aiida-quantumespresso/src/aiida_quantumespresso/common/hubbard.py in from_tuple(hubbard_parameters)
    106             'hubbard_type',
    107         ]
--> 108         return HubbardParameters(**dict(zip(keys, hubbard_parameters)))
    109 
    110 

/opt/conda/lib/python3.9/site-packages/pydantic/main.py in __init__(self, **data)
    173         # `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks
    174         __tracebackhide__ = True
--> 175         self.__pydantic_validator__.validate_python(data, self_instance=self)
    176 
    177     # The following line sets a flag that we use to determine when `__init__` gets overridden by the user

ValidationError: 2 validation errors for HubbardParameters
atom_manifold
  Value error, invalid length ``4``. Only 2 or 5. [type=value_error, input_value='None', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/value_error
neighbour_manifold
  Value error, invalid length ``4``. Only 2 or 5. [type=value_error, input_value='None', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/value_error
```
</details>

<details>
<summary>Environment fingerprint</summary>
<pre>eNptV0uP4zYM_iuD9FobfiTzurV7K7rAttPHoSgCWaYTTWRJI8nJeIv976VIOfGgPZqiKPIj-ZH-Z3MGH5Q1m-f6-43TIg7Wj5vn
fzbCy6OKIOPkYfP81-Z-26m4-X6z-Rv15ni0Zn-9umnLp7Ju8fQm-q6-e_n85e5FxLsfnL9rHu6q7XPdPtdPd7__9umuqZrt5hua
EvIkDhDoSSkhBNVpKNx8GMFEFG-qsiq3aFoo1YvC4cPWzSivy3otDzD1lsS7srqK3yZh4jRCcB5Np_Nteb86P6vO2yBvFm9HF2GM
Av9U4UlTNv93UlysPw3aXgLptDcdLboCtCH367JZi8dBFDJIulI1bVlXVbs6379BOtmivKzEdn1yUf0BYth3IsDyoCDbeCpCBE_v
PXAqhAmqOcZRU2SYH5LNbIQUc87YWls2DesEU0s_u7igScIYPXncZiR-FB1ocqLmax0m0lkfQxmFH5QGus3KHYgpqmHSwU5uS0nA
W8nzzp7gSGa2ZfKlm0Z3pjgYm7p5QuknIY_wyZrorWZIW3pTJnm0Vgey2VA9SPD4lmITW0SDhMPhTEFuySF5FL4nFHbZxSQJEAuD
5S-0-ko-tLkg8JVRmYGrJOFGQqutF6MgEVYViUy0k8_FxLhIi_FghaPoIZemnKXOucrg9SpErToSteVjkpjAXUbg3LOWlQij5qao
H0gGGlKjOBGPhAHHB6NQen_GQHoRrec8sf6UOkhJ8pBRTMnSVp44YH5qwEhuwO4YhmFiMsCbFQmOdc2-8KvHHUWe0sbf0yjM4BWY
XhMk1U2MCJNpxlL1GIMaZnJ0V7b3JDOCrD2kjzGRBF_Cticf1ZjqDWErRogCA03q9-UjW8QYrRnUgUzyw8rN1kU01QO53SzS6GGR
NCzJrVbAe0Tvoc_skJ59FV5IW0otQki8dS2q5QChw2vkS7W-MUxG3jBliF4BnAEuK3b8J2Vesam5-FLpvtqOS6PO75yEBkVcV-
UaO8HslaFQd7nGTuqigtXcS-nmDoVa-FOO5Ik-0VFpe5D0HIOk4V313Dx14qaUCm0Pk58yuTQksAFuXF9n6hvRfm8vplCxyKXARj
_jweRexAC5FFvSjk7bXPdY9RTt2E9er2hzRDTnpZcRtQeSecAnsM8zmo9LBY5u5EZYPDIiBiwS0mEVAzGx9jtTHsFnDvqs4JL9Td
1nju0CL30iRmDOZJeztKqjOs8nO0VpR1geL50NManyhMvp4Y5zmMEYRaeZeFuCwwnTi5CHTQrdHR6rqmJ7dZZECHHVurdp2Cz07Z
TGgcTdxhh8UYb5vqFnlOP5ki2cDonZuCo4WcsW0CvPpdoSuVGuZqbMOitOh8O8mrlOL_2fPjBJCMioIncxa4T5YEROcLaSR-
_y1WFRsrucsC_zJzX8-mdmN_Jk7nGqK1kgYUcEdgGtzmdRFMEdlXkvIhI3LBOjJWPXvQL1d_mKRoT2NGZz5bEYa-kAZlV8bOHz_P
LLz3kQEKKz8_YVN6VCOLWqEeQVztbjkmESFGl8F1zlTVmvVBGu84obsjDFg6lYw5wPkLN5VGYmy_I887fXOEi64sj244mHQ1qOsJ
VD5t-VsYADxqhpJIPV-ho2AGDN50VkdXAWXqXaDqsJyrMMXY5LH11t2VcpRpeBT7pvUCyNvUTmQfQj7H3iYk8xb7f54G3CN_P-1X
yQkRXcUuJqYvlBtk-P96uh4JUkwmhzNoNUS0Vy-wTp2b-FRV9AeogvOFd5rC8NHABObqGfJxpbH9Bj6gwwnvNyUWVBnNwS8P0uD7
dg7KUTWuNWN44fspz4DPo0ZYQywFtZ5ra0XgWFxJxlZMgdmGEXpRdqDZ7rfIsE-x7n68Hkbaa-
ytNDHmescE7DEbRbUd5HjR7Oq_PmP-epLrNCk9P_UeE1XNn7_47f4sp8-5_jAFh2uLkhIVy33poSFuZxSWnyCktQSEVT5RExTZbi
MVWYwyTIqFcjPVoGKq296dMLFZG6A7Egry74dh7Fu-t3cYEupO6MC9GlaOLs0Lc9rRRLt20zV8SvuTeJapI2Lgs44DDFUV07KZUU
Egfms13NiT8E7kHzamaelY8TjhjqtAY941XxAiLsV-
s_erUjcdd7hTVZ4FqGFe2X_7l0Rtp7h9DaXsnbyOKILvhbZfN_Ahfn-6hD2pZFZpKk9VU5x5eS0W_f_gXuVSFW</pre>
</details>

**By submitting this issue I confirm that I am aware that this information can
potentially be used to determine what kind of calculation was performed at the
time of error.**

**Comment by AndresOrtegaGuerrero** [comment]
@edan-bainglass somehow I got this one , while trying to submit a molecule and using DFT+U , i wonder if you can reproduce it ?

**Comment by edan-bainglass** [comment]
That is very odd. Okay, will try to reproduce tomorrow morning.

**Comment by edan-bainglass** [comment]
@AndresOrtegaGuerrero can we close this one?
