### ISSUE TITLE
Keep PBEsol as the default even when switching to spin-orbit coupling

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [aiidalab/aiidalab-qe#952]
If I activate SOC, the functional is changed to PBE. If I deactivate, it jumps back to PBEsol. I think it should always be the same

**Comment by jjyutm4532** [comment]
Hello, we tried to solve the issue.

This is what we did:

Add a new trait 'functional' to keep track of the selected functional. Update the get_model_state and set_model_state methods to handle the functional setting. Modify the spin_orbit setter to preserve the functional when changing SOC.

You can review changes in this commit: https://github.com/jjyutm4532/aiidalab-aiidalab-qe-952/commit/339c1534f6cd03c64345a679739f2d609f07933b.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
