### ISSUE TITLE
Periodicity "select" button confusing

### ISSUE THREAD

**Issue by aj0337** [aiidalab/aiidalab-qe#961]
![image](https://github.com/user-attachments/assets/0f3c78c0-3470-4c9e-bab7-c9984b3aab67)

It was unclear that I had to click "Select" in order to apply my changes. Perhaps a green "Apply" button would make it clearer that the user needs to click it in order for the changes to periodicity to take effect.
App version v24.10.0a4

**Comment by edan-bainglass** [comment]
Thanks @aj0337. @AndresOrtegaGuerrero could you please have a look at this?

**Comment by AndresOrtegaGuerrero** [comment]
The periodicity widget was already modified , so the image doesn't show the current status.

**Comment by edan-bainglass** [comment]
> The periodicity widget was already modified , so the image doesn't show the current status.

@AndresOrtegaGuerrero though you are correct that the image no longer reflects the current state, the issue at hand remains - we are still using a blue "Select" button, which I believe was the source of @aj0337's confusion. I agree with the suggestion above. If removing the button is not an option (for performance reasons), could we opt for an "Apply" button? "Select" appears to be unclear.
