### ISSUE TITLE
Improve home page of the app (in the main list of apps)

### ISSUE THREAD

**Issue by edan-bainglass** [aiidalab/aiidalab-qe#983]
This is just to give a sense of what I have in mind (images done by Dall-E... need of course to be redone)

Each of the 3 is a clickable button; outer border needed, or anyway graphical element to make it clear it's a clickable button and not just a drawing (we got the comment already that now the QE logo does not look like something you have to click)

![Image](https://github.com/user-attachments/assets/0eb4202d-286d-4b09-a476-8589aebdecb2)

**NOTE**: we discussed and we want to have the text under the buttons to be (in this new order):
* Run new calculation
* Calculation history
* Manage plugins

Suggestion: to uniform the style, also for the first button. So we should have a similar icon, but with a little QE logo inside, rather than the QE logo only (and maybe the logo without the text "Quantum ESPRESSO".

**Comment by edan-bainglass** [comment]
I agree with 99% of this issue, with the actual design I suppose to be discussed soon?

The part I'm iffy about is the border. Can we think of an alternative? Take this google new tab page for example:

![Image](https://github.com/user-attachments/assets/db743a02-e35b-4390-aec0-133aaa6fa92d)

The buttons aren't bordered, unless you count the circle, which I think is a nice touch. A hover border effect is, however, present, as seen on the Calendar button. Also a nice touch! We could think of something like this? This approach also suggests that maybe we don't need the three buttons to be so uniform, as long as their wrapping design is uniform (like a circular bounding container, for example)

@giovannipizzi @cpignedoli thoughts?

**Comment by edan-bainglass** [comment]
Something like this?

![Image](https://github.com/user-attachments/assets/aa6b4744-6fe7-4a4d-b1d6-380e9a42a3b9)

**Comment by giovannipizzi** [comment]
I like it!

**Comment by cpignedoli** [comment]
super!!
