### ISSUE TITLE
Cannot launch v 21.07.0b3 QE-app

### ISSUE THREAD

**Issue by mkotiuga** [aiidalab/aiidalab-qe#99]
After making my github membership public , I updated to version 21.07.0b3  and didn’t do anything else. I cannot launch the app (see screen shot below) Not sure if this is a ‘global issue’ or just one on my end?

![image](https://user-images.githubusercontent.com/11949506/126986367-bc46c8f2-c96b-44ef-809f-603108c03bcb.png)

**Comment by csadorf** [comment]
No, it's an issue with the beta version dependency specification, I'll push a fix.

**Comment by csadorf** [comment]
@mkotiuga Please open the "Terminal" and execute
```terminal
pip install -U aiidalab-widgets-base
```
That should resolve the issue.

**Comment by mkotiuga** [comment]
thanks @csadorf  - that worked

**Comment by csadorf** [comment]
This issue should also be resolved with #100 .
