### ISSUE TITLE
Why do we need an 'override' checkbox?

### ISSUE THREAD

**Issue by edan-bainglass** [aiidalab/aiidalab-qe#991]
If I activate it, shouldn't all parameters be the defaults?
If not, it's a bit confusing, because maybe I want simply to activate spin-orbit but then some other behavior changes.

If instead they are just the defaults, it's strange that I can't do anything (I was suprised myself that the spin-orbit toggle was not working) until I check this box placed in a special top-right cornet.

I vote to just remove it and keep all buttons, checkboxes, ... active.

**NOTE**: if removed, we should adapt the text below removing at least 2 occurrences of "Tick the box to override the default,"

Rather, replace with a 'Reset defaults' button.

**Comment by AndresOrtegaGuerrero** [comment]
An additional consideration for this implementation is ensuring that, when running a magnetic system, magnetization is not assigned as zero for all elements (Kinds) by default. Otherwise, this would prevent the system from converging to a magnetic solution.
